DROP TABLE IF EXISTS Club; 
CREATE TABLE Club (Club_id INT, Club_name VARCHAR(20));

INSERT into Clubs values (0, "");
INSERT into Clubs values (1, "FC St. Gallen");
INSERT into Clubs values (2, "Fleetwood Town");
INSERT into Clubs values (3, "St. Patrick's Athletic");
INSERT into Clubs values (4, "Ferrara (SPAL)");
INSERT into Clubs values (5, "Bologna");
INSERT into Clubs values (6, "Torino");
INSERT into Clubs values (7, "Adelaide United");
INSERT into Clubs values (8, "Independiente Santa Fe");
INSERT into Clubs values (9, "Aalborg BK");
INSERT into Clubs values (10, "Al Nassr");
INSERT into Clubs values (11, "Royal Excel Mouscron");
INSERT into Clubs values (12, "Le Havre AC");
INSERT into Clubs values (13, "Rochdale");
INSERT into Clubs values (14, "Borussia Mönchengladbach");
INSERT into Clubs values (15, "Liverpool");
INSERT into Clubs values (16, "Águilas Doradas");
INSERT into Clubs values (17, "Yeovil Town");
INSERT into Clubs values (18, "Real Zaragoza");
INSERT into Clubs values (19, "Gimnàstic de Tarragona");
INSERT into Clubs values (20, "Associação Atlética Ponte Preta");
INSERT into Clubs values (21, "Colorado Rapids");
INSERT into Clubs values (22, "Gimnasia y Esgrima La Plata");
INSERT into Clubs values (23, "Inter");
INSERT into Clubs values (24, "SK Rapid Wien");
INSERT into Clubs values (25, "Leicester City");
INSERT into Clubs values (26, "Bristol Rovers");
INSERT into Clubs values (27, "PAOK Thessaloniki");
INSERT into Clubs values (28, "Atletico Nacional Medellin");
INSERT into Clubs values (29, "Al Ittihad");
INSERT into Clubs values (30, "RC Strasbourg");
INSERT into Clubs values (31, "RC Celta de Vigo");
INSERT into Clubs values (32, "Halmstads BK");
INSERT into Clubs values (33, "Hibernian");
INSERT into Clubs values (34, "Club Atlético Patronato");
INSERT into Clubs values (35, "Sligo Rovers");
INSERT into Clubs values (36, "FC Twente");
INSERT into Clubs values (37, "Chesterfield");
INSERT into Clubs values (38, "Brescia");
INSERT into Clubs values (39, "FC Basel");
INSERT into Clubs values (40, "GFC Ajaccio");
INSERT into Clubs values (41, "Western Sydney Wanderers");
INSERT into Clubs values (42, "Defensa y Justicia");
INSERT into Clubs values (43, "Ross County FC");
INSERT into Clubs values (44, "Notts County");
INSERT into Clubs values (45, "Montpellier Hérault SC");
INSERT into Clubs values (46, "Sangju Sangmu FC");
INSERT into Clubs values (47, "Cambridge United");
INSERT into Clubs values (48, "SC Fortuna Köln");
INSERT into Clubs values (49, "Club Atlético Lanús");
INSERT into Clubs values (50, "Zenit St. Petersburg");
INSERT into Clubs values (51, "Brighton & Hove Albion");
INSERT into Clubs values (52, "LOSC Lille");
INSERT into Clubs values (53, "Rosario Central");
INSERT into Clubs values (54, "Sheffield Wednesday");
INSERT into Clubs values (55, "Club Brugge KV");
INSERT into Clubs values (56, "NAC Breda");
INSERT into Clubs values (57, "FC Lorient");
INSERT into Clubs values (58, "Lech Poznań");
INSERT into Clubs values (59, "Valencia CF");
INSERT into Clubs values (60, "FC Augsburg");
INSERT into Clubs values (61, "Kilmarnock");
INSERT into Clubs values (62, "Manchester City");
INSERT into Clubs values (63, "Asociacion Deportivo Cali");
INSERT into Clubs values (64, "Wolfsberger AC");
INSERT into Clubs values (65, "Limerick FC");
INSERT into Clubs values (66, "Cádiz C.F.");
INSERT into Clubs values (67, "Deportivo Toluca");
INSERT into Clubs values (68, "Hellas Verona");
INSERT into Clubs values (69, "Frosinone");
INSERT into Clubs values (70, "Olympiakos CFP");
INSERT into Clubs values (71, "En Avant de Guingamp");
INSERT into Clubs values (72, "Deportes Tolima");
INSERT into Clubs values (73, "Ventforet Kofu");
INSERT into Clubs values (74, "CD Los Millionarios Bogota");
INSERT into Clubs values (75, "Querétaro");
INSERT into Clubs values (76, "RC Lens");
INSERT into Clubs values (77, "Odds BK");
INSERT into Clubs values (78, "Swindon Town");
INSERT into Clubs values (79, "Atiker Konyaspor");
INSERT into Clubs values (80, "Vancouver Whitecaps FC");
INSERT into Clubs values (81, "Crotone");
INSERT into Clubs values (82, "Colon de Santa Fe");
INSERT into Clubs values (83, "Perugia");
INSERT into Clubs values (84, "Forest Green");
INSERT into Clubs values (85, "Chicago Fire Soccer Club");
INSERT into Clubs values (86, "Cruzeiro");
INSERT into Clubs values (87, "SG Sonnenhof Großaspach");
INSERT into Clubs values (88, "Molde FK");
INSERT into Clubs values (89, "Bayer 04 Leverkusen");
INSERT into Clubs values (90, "FC Dallas");
INSERT into Clubs values (91, "Tigres FC");
INSERT into Clubs values (92, "Sogndal");
INSERT into Clubs values (93, "Cremonese");
INSERT into Clubs values (94, "Melbourne City");
INSERT into Clubs values (95, "US Orléans Loiret Football");
INSERT into Clubs values (96, "Zagłębie Lubin");
INSERT into Clubs values (97, "New York City Football Club");
INSERT into Clubs values (98, "SC Paderborn 07");
INSERT into Clubs values (99, "Estoril Praia");
INSERT into Clubs values (100, "Argentinos Juniors");
INSERT into Clubs values (101, "Sportfreunde Lotte");
INSERT into Clubs values (102, "Fluminense Football Club");
INSERT into Clubs values (103, "US Quevilly-Rouen");
INSERT into Clubs values (104, "F.C. Tokyo");
INSERT into Clubs values (105, "Atlético Madrid");
INSERT into Clubs values (106, "Banfield");
INSERT into Clubs values (107, "FC Seoul");
INSERT into Clubs values (108, "Associação Chapecoense de Futebol");
INSERT into Clubs values (109, "Finn Harps");
INSERT into Clubs values (110, "Sheffield United");
INSERT into Clubs values (111, "ES Troyes AC");
INSERT into Clubs values (112, "Kaizer Chiefs");
INSERT into Clubs values (113, "Bradford City");
INSERT into Clubs values (114, "Botafogo de Futebol e Regatas");
INSERT into Clubs values (115, "Incheon United FC");
INSERT into Clubs values (116, "FC Ural");
INSERT into Clubs values (117, "Hamburger SV");
INSERT into Clubs values (118, "Bury");
INSERT into Clubs values (119, "Sparta Praha");
INSERT into Clubs values (120, "Minnesota Thunder");
INSERT into Clubs values (121, "Derry City");
INSERT into Clubs values (122, "FK Austria Wien");
INSERT into Clubs values (123, "Clube Atlético Mineiro");
INSERT into Clubs values (124, "Cruz Azul");
INSERT into Clubs values (125, "Heart of Midlothian");
INSERT into Clubs values (126, "Wycombe Wanderers");
INSERT into Clubs values (127, "KRC Genk");
INSERT into Clubs values (128, "Avaí Futebol Clube");
INSERT into Clubs values (129, "Waasland-Beveren");
INSERT into Clubs values (130, "Albirex Niigata");
INSERT into Clubs values (131, "Atlético Clube Goianiense");
INSERT into Clubs values (132, "Crewe Alexandra");
INSERT into Clubs values (133, "SpVgg Unterhaching");
INSERT into Clubs values (134, "Atalanta");
INSERT into Clubs values (135, "Dundalk");
INSERT into Clubs values (136, "Fulham");
INSERT into Clubs values (137, "Millwall");
INSERT into Clubs values (138, "Santos Laguna");
INSERT into Clubs values (139, "AIK Solna");
INSERT into Clubs values (140, "Universidad Católica");
INSERT into Clubs values (141, "Newcastle United");
INSERT into Clubs values (142, "IFK Norrköping");
INSERT into Clubs values (143, "CD Numancia");
INSERT into Clubs values (144, "Grupo Desportivo de Chaves");
INSERT into Clubs values (145, "Heracles Almelo");
INSERT into Clubs values (146, "Sampdoria");
INSERT into Clubs values (147, "SG Dynamo Dresden");
INSERT into Clubs values (148, "Real Salt Lake");
INSERT into Clubs values (149, "Unión de Santa Fe");
INSERT into Clubs values (150, "Patriotas Boyacá FC");
INSERT into Clubs values (151, "Al Hilal");
INSERT into Clubs values (152, "Jönköpings Södra IF");
INSERT into Clubs values (153, "VfB Stuttgart");
INSERT into Clubs values (154, "Gençlerbirliği SK");
INSERT into Clubs values (155, "Blackpool");
INSERT into Clubs values (156, "Yokohama F. Marinos");
INSERT into Clubs values (157, "SC Freiburg");
INSERT into Clubs values (158, "Feyenoord");
INSERT into Clubs values (159, "Genoa");
INSERT into Clubs values (160, "Monterrey");
INSERT into Clubs values (161, "FC Thun");
INSERT into Clubs values (162, "Aalesunds FK");
INSERT into Clubs values (163, "Jeju United FC");
INSERT into Clubs values (164, "Melbourne Victory");
INSERT into Clubs values (165, "Barnet");
INSERT into Clubs values (166, "La Spezia");
INSERT into Clubs values (167, "Roda JC Kerkrade");
INSERT into Clubs values (168, "Wisła Kraków");
INSERT into Clubs values (169, "Real Sociedad");
INSERT into Clubs values (170, "Doncaster Rovers");
INSERT into Clubs values (171, "Chamois Niortais FC");
INSERT into Clubs values (172, "La Equidad");
INSERT into Clubs values (173, "Granada CF");
INSERT into Clubs values (174, "Deportivo Pasto");
INSERT into Clubs values (175, "FC Lausanne-Sports");
INSERT into Clubs values (176, "Kasimpaşa SK");
INSERT into Clubs values (177, "Korona Kielce");
INSERT into Clubs values (178, "Strømsgodset IF");
INSERT into Clubs values (179, "SKN St. Pölten");
INSERT into Clubs values (180, "SK Sturm Graz");
INSERT into Clubs values (181, "Hertha BSC Berlin");
INSERT into Clubs values (182, "Drogheda United");
INSERT into Clubs values (183, "CD Huachipato");
INSERT into Clubs values (184, "Vålerenga Fotball");
INSERT into Clubs values (185, "Celtic");
INSERT into Clubs values (186, "AC Ajaccio");
INSERT into Clubs values (187, "Jagiellonia Białystok");
INSERT into Clubs values (188, "Sanfrecce Hiroshima");
INSERT into Clubs values (189, "Bournemouth");
INSERT into Clubs values (190, "Clermont Foot 63");
INSERT into Clubs values (191, "Roma");
INSERT into Clubs values (192, "FSV Zwickau");
INSERT into Clubs values (193, "AS Saint-Étienne");
INSERT into Clubs values (194, "AZ Alkmaar");
INSERT into Clubs values (195, "Charlton Athletic");
INSERT into Clubs values (196, "Getafe CF");
INSERT into Clubs values (197, "Olympique Lyonnais");
INSERT into Clubs values (198, "FC Erzgebirge Aue");
INSERT into Clubs values (199, "San Jose Earthquakes");
INSERT into Clubs values (200, "Milan");
INSERT into Clubs values (201, "Vercelli");
INSERT into Clubs values (202, "Levante UD");
INSERT into Clubs values (203, "Crawley Town");
INSERT into Clubs values (204, "Morecambe");
INSERT into Clubs values (205, "Coritiba Foot Ball Club");
INSERT into Clubs values (206, "Southend United");
INSERT into Clubs values (207, "Tromsø IL");
INSERT into Clubs values (208, "Daegu FC");
INSERT into Clubs values (209, "Guadalajara");
INSERT into Clubs values (210, "Górnik Zabrze");
INSERT into Clubs values (211, "Chievo Verona");
INSERT into Clubs values (212, "Atlético Tucumán");
INSERT into Clubs values (213, "Bristol City");
INSERT into Clubs values (214, "Exeter City");
INSERT into Clubs values (215, "Omiya Ardija");
INSERT into Clubs values (216, "Reading");
INSERT into Clubs values (217, "Grasshopper Club Zürich");
INSERT into Clubs values (218, "RC Deportivo de La Coruña");
INSERT into Clubs values (219, "AC Horsens");
INSERT into Clubs values (220, "VfL Osnabrück");
INSERT into Clubs values (221, "Júbilo Iwata");
INSERT into Clubs values (222, "Columbus Crew SC");
INSERT into Clubs values (223, "FC Barcelona B");
INSERT into Clubs values (224, "Hallescher FC");
INSERT into Clubs values (225, "Málaga CF");
INSERT into Clubs values (226, "River Plate");
INSERT into Clubs values (227, "Rayo Vallecano");
INSERT into Clubs values (228, "Arsenal de Sarandí");
INSERT into Clubs values (229, "Toronto FC");
INSERT into Clubs values (230, "CD Tenerife");
INSERT into Clubs values (231, "Cerezo Osaka");
INSERT into Clubs values (232, "Eintracht Braunschweig");
INSERT into Clubs values (233, "1. FC Union Berlin");
INSERT into Clubs values (234, "Rot-Weiß Erfurt");
INSERT into Clubs values (235, "Oldham Athletic");
INSERT into Clubs values (236, "Lillestrøm SK");
INSERT into Clubs values (237, "Moreirense FC");
INSERT into Clubs values (238, "Curicó Unido");
INSERT into Clubs values (239, "SV Zulte-Waregem");
INSERT into Clubs values (240, "KV Oostende");
INSERT into Clubs values (241, "Stoke City");
INSERT into Clubs values (242, "Arsenal");
INSERT into Clubs values (243, "Luton Town");
INSERT into Clubs values (244, "Stade Brestois 29");
INSERT into Clubs values (245, "Willem II");
INSERT into Clubs values (246, "FC Ufa");
INSERT into Clubs values (247, "CD Once Caldas Manizales");
INSERT into Clubs values (248, "New York Red Bulls");
INSERT into Clubs values (249, "Atlanta United FC");
INSERT into Clubs values (250, "Newcastle Jets");
INSERT into Clubs values (251, "Al Shabab");
INSERT into Clubs values (252, "Ettifaq FC");
INSERT into Clubs values (253, "Akhisar Belediyespor");
INSERT into Clubs values (254, "Al Batin");
INSERT into Clubs values (255, "Colchester United");
INSERT into Clubs values (256, "SK Brann");
INSERT into Clubs values (257, "FC Rostov");
INSERT into Clubs values (258, "Bourg en Bresse Péronnas 01");
INSERT into Clubs values (259, "Philadelphia Union");
INSERT into Clubs values (260, "Everton");
INSERT into Clubs values (261, "FC Helsingør");
INSERT into Clubs values (262, "1. FC Nürnberg");
INSERT into Clubs values (263, "Cork City");
INSERT into Clubs values (264, "Arsenal Tula");
INSERT into Clubs values (265, "Club Tijuana");
INSERT into Clubs values (266, "Palermo");
INSERT into Clubs values (267, "Temperley");
INSERT into Clubs values (268, "Ipswich Town");
INSERT into Clubs values (269, "VfR Aalen");
INSERT into Clubs values (270, "Northampton Town");
INSERT into Clubs values (271, "SpVgg Greuther Fürth");
INSERT into Clubs values (272, "Sandefjord Fotball");
INSERT into Clubs values (273, "Preston North End");
INSERT into Clubs values (274, "SD Huesca");
INSERT into Clubs values (275, "BSC Young Boys");
INSERT into Clubs values (276, "Tottenham Hotspur");
INSERT into Clubs values (277, "Evkur Yeni Malatyaspor");
INSERT into Clubs values (278, "F.B.C. Unione Venezia");
INSERT into Clubs values (279, "Empoli");
INSERT into Clubs values (280, "Dundee FC");
INSERT into Clubs values (281, "U.N.A.M.");
INSERT into Clubs values (282, "Rosenborg BK");
INSERT into Clubs values (283, "Santos Futebol Clube");
INSERT into Clubs values (284, "MSV Duisburg");
INSERT into Clubs values (285, "Al Fayha");
INSERT into Clubs values (286, "Vitória Setúbal");
INSERT into Clubs values (287, "CD Leganés");
INSERT into Clubs values (288, "Suwon Samsung Bluewings");
INSERT into Clubs values (289, "Brisbane Roar");
INSERT into Clubs values (290, "FC København");
INSERT into Clubs values (291, "Real Sporting de Gijón");
INSERT into Clubs values (292, "Bursaspor");
INSERT into Clubs values (293, "Göztepe");
INSERT into Clubs values (294, "Amiens SC Football");
INSERT into Clubs values (295, "Pachuca");
INSERT into Clubs values (296, "Burton Albion");
INSERT into Clubs values (297, "Amkar Perm");
INSERT into Clubs values (298, "Vegalta Sendai");
INSERT into Clubs values (299, "1. FC Kaiserslautern");
INSERT into Clubs values (300, "Carlisle United");
INSERT into Clubs values (301, "Boavista FC");
INSERT into Clubs values (302, "Shamrock Rovers");
INSERT into Clubs values (303, "UD Almería");
INSERT into Clubs values (304, "Milton Keynes Dons");
INSERT into Clubs values (305, "Puebla");
INSERT into Clubs values (306, "Randers FC");
INSERT into Clubs values (307, "Östersunds FK");
INSERT into Clubs values (308, "Everton de Viña del Mar");
INSERT into Clubs values (309, "Atlético Huila");
INSERT into Clubs values (310, "FC Groningen");
INSERT into Clubs values (311, "Wigan Athletic");
INSERT into Clubs values (312, "Vélez Sarsfield");
INSERT into Clubs values (313, "CD Feirense");
INSERT into Clubs values (314, "FC St. Pauli");
INSERT into Clubs values (315, "Grimsby Town");
INSERT into Clubs values (316, "Deportivo Alavés");
INSERT into Clubs values (317, "AS Nancy Lorraine");
INSERT into Clubs values (318, "Blackburn Rovers");
INSERT into Clubs values (319, "Sporting Kansas City");
INSERT into Clubs values (320, "Portimonense SC");
INSERT into Clubs values (321, "SD Eibar");
INSERT into Clubs values (322, "CA Osasuna");
INSERT into Clubs values (323, "Necaxa");
INSERT into Clubs values (324, "Kawasaki Frontale");
INSERT into Clubs values (325, "Sassuolo");
INSERT into Clubs values (326, "Paris Saint-Germain");
INSERT into Clubs values (327, "Rangers");
INSERT into Clubs values (328, "Rotherham United");
INSERT into Clubs values (329, "Sint-Truidense VV");
INSERT into Clubs values (330, "RCD Espanyol");
INSERT into Clubs values (331, "Udinese");
INSERT into Clubs values (332, "FC Barcelona");
INSERT into Clubs values (333, "Novara");
INSERT into Clubs values (334, "Plymouth Argyle");
INSERT into Clubs values (335, "Avellino");
INSERT into Clubs values (336, "Sydney FC");
INSERT into Clubs values (337, "CD Antofagasta");
INSERT into Clubs values (338, "Villarreal CF");
INSERT into Clubs values (339, "Pohang Steelers");
INSERT into Clubs values (340, "Fiorentina");
INSERT into Clubs values (341, "Dinamo Moscow");
INSERT into Clubs values (342, "Lazio");
INSERT into Clubs values (343, "Mansfield Town");
INSERT into Clubs values (344, "Hannover 96");
INSERT into Clubs values (345, "Tours FC");
INSERT into Clubs values (346, "FC Krasnodar");
INSERT into Clubs values (347, "Oxford United");
INSERT into Clubs values (348, "Clube Atlético Paranaense");
INSERT into Clubs values (349, "Real Madrid CF");
INSERT into Clubs values (350, "Gangwon FC");
INSERT into Clubs values (351, "Cittadella");
INSERT into Clubs values (352, "Lorca Deportiva CF");
INSERT into Clubs values (353, "Fortuna Düsseldorf");
INSERT into Clubs values (354, "CF Reus Deportiu");
INSERT into Clubs values (355, "Urawa Red Diamonds");
INSERT into Clubs values (356, "Orlando City Soccer Club");
INSERT into Clubs values (357, "Pescara");
INSERT into Clubs values (358, "Crystal Palace");
INSERT into Clubs values (359, "Antalyaspor");
INSERT into Clubs values (360, "Seattle Sounders FC");
INSERT into Clubs values (361, "Tiburones Rojos de Veracruz");
INSERT into Clubs values (362, "Stevenage");
INSERT into Clubs values (363, "FC Utrecht");
INSERT into Clubs values (364, "Godoy Cruz");
INSERT into Clubs values (365, "Audax Italiano");
INSERT into Clubs values (366, "Manchester United");
INSERT into Clubs values (367, "Sporting Charleroi");
INSERT into Clubs values (368, "Nottingham Forest");
INSERT into Clubs values (369, "Valenciennes FC");
INSERT into Clubs values (370, "Central Coast Mariners");
INSERT into Clubs values (371, "Peterborough United");
INSERT into Clubs values (372, "Royal Antwerp FC");
INSERT into Clubs values (373, "Estudiantes de La Plata");
INSERT into Clubs values (374, "Salernitana");
INSERT into Clubs values (375, "KAS Eupen");
INSERT into Clubs values (376, "Hammarby IF");
INSERT into Clubs values (377, "Dijon FCO");
INSERT into Clubs values (378, "Envigado FC");
INSERT into Clubs values (379, "Real Betis Balompié");
INSERT into Clubs values (380, "Atlético Bucaramanga");
INSERT into Clubs values (381, "SCR Altach");
INSERT into Clubs values (382, "San Luis de Quillota");
INSERT into Clubs values (383, "Santiago Wanderers");
INSERT into Clubs values (384, "SC Preußen Münster");
INSERT into Clubs values (385, "Southampton");
INSERT into Clubs values (386, "Vitória Guimarães");
INSERT into Clubs values (387, "Cheltenham Town");
INSERT into Clubs values (388, "KV Mechelen");
INSERT into Clubs values (389, "Rio Ave FC");
INSERT into Clubs values (390, "Vitória ");
INSERT into Clubs values (391, "FK Haugesund");
INSERT into Clubs values (392, "Terek Grozny");
INSERT into Clubs values (393, "Portsmouth");
INSERT into Clubs values (394, "SC Braga");
INSERT into Clubs values (395, "Middlesbrough");
INSERT into Clubs values (396, "Watford");
INSERT into Clubs values (397, "Toulouse FC");
INSERT into Clubs values (398, "CD Lugo");
INSERT into Clubs values (399, "PSV");
INSERT into Clubs values (400, "Jeonnam Dragons");
INSERT into Clubs values (401, "Gillingham");
INSERT into Clubs values (402, "CD Universidad de Concepción");
INSERT into Clubs values (403, "AFC Eskilstuna");
INSERT into Clubs values (404, "SM Caen");
INSERT into Clubs values (405, "Lechia Gdańsk");
INSERT into Clubs values (406, "Cardiff City");
INSERT into Clubs values (407, "Angers SCO");
INSERT into Clubs values (408, "OGC Nice");
INSERT into Clubs values (409, "VfL Wolfsburg");
INSERT into Clubs values (410, "Sarpsborg 08 FF");
INSERT into Clubs values (411, "Stade de Reims");
INSERT into Clubs values (412, "Śląsk Wrocław");
INSERT into Clubs values (413, "Grêmio Foot-Ball Porto Alegrense");
INSERT into Clubs values (414, "Jeonbuk Hyundai Motors");
INSERT into Clubs values (415, "Ajax");
INSERT into Clubs values (416, "Werder Bremen II");
INSERT into Clubs values (417, "Cagliari");
INSERT into Clubs values (418, "SV Darmstadt 98");
INSERT into Clubs values (419, "Örebro SK");
INSERT into Clubs values (420, "Club Atlas");
INSERT into Clubs values (421, "Hamilton Academical FC");
INSERT into Clubs values (422, "Arka Gdynia");
INSERT into Clubs values (423, "Brentford");
INSERT into Clubs values (424, "Hobro IK");
INSERT into Clubs values (425, "Hokkaido Consadole Sapporo");
INSERT into Clubs values (426, "HJK Helsinki");
INSERT into Clubs values (427, "VfL Bochum");
INSERT into Clubs values (428, "Real Valladolid");
INSERT into Clubs values (429, "Tigres U.A.N.L.");
INSERT into Clubs values (430, "FC Metz");
INSERT into Clubs values (431, "Accrington Stanley");
INSERT into Clubs values (432, "Al Faisaly");
INSERT into Clubs values (433, "São Paulo Futebol Clube");
INSERT into Clubs values (434, "Trabzonspor");
INSERT into Clubs values (435, "Galatasaray SK");
INSERT into Clubs values (436, "CD Palestino");
INSERT into Clubs values (437, "FC SKA-Energiya Khabarovsk");
INSERT into Clubs values (438, "Houston Dynamo");
INSERT into Clubs values (439, "AEK Athens");
INSERT into Clubs values (440, "LA Galaxy");
INSERT into Clubs values (441, "FC Zürich");
INSERT into Clubs values (442, "Jaguares Fútbol Club");
INSERT into Clubs values (443, "Independiente");
INSERT into Clubs values (444, "Rubin Kazan");
INSERT into Clubs values (445, "Ulsan Hyundai Horang-i");
INSERT into Clubs values (446, "Sociedade Esportiva Palmeiras");
INSERT into Clubs values (447, "Stade Rennais FC");
INSERT into Clubs values (448, "Beşiktaş JK");
INSERT into Clubs values (449, "Spartak Moscow");
INSERT into Clubs values (450, "Osmanlıspor");
INSERT into Clubs values (451, "Al Raed");
INSERT into Clubs values (452, "Borussia Dortmund");
INSERT into Clubs values (453, "Termalica Bruk-Bet Nieciecza");
INSERT into Clubs values (454, "Standard de Liège");
INSERT into Clubs values (455, "Cesena");
INSERT into Clubs values (456, "Excelsior");
INSERT into Clubs values (457, "San Martín de San Juan");
INSERT into Clubs values (458, "Wolverhampton Wanderers");
INSERT into Clubs values (459, "Newport County");
INSERT into Clubs values (460, "Würzburger FV");
INSERT into Clubs values (461, "Belgrano de Córdoba");
INSERT into Clubs values (462, "CSKA Moscow");
INSERT into Clubs values (463, "TSG 1899 Hoffenheim");
INSERT into Clubs values (464, "Norwich City");
INSERT into Clubs values (465, "Sagan Tosu");
INSERT into Clubs values (466, "Orlando Pirates");
INSERT into Clubs values (467, "Hull City");
INSERT into Clubs values (468, "Al Qadisiyah");
INSERT into Clubs values (469, "Viking FK");
INSERT into Clubs values (470, "CD O'Higgins");
INSERT into Clubs values (471, "Al Fateh");
INSERT into Clubs values (472, "Club Atlético Huracán");
INSERT into Clubs values (473, "Alianza Petrolera");
INSERT into Clubs values (474, "Aberdeen");
INSERT into Clubs values (475, "Albacete Balompié");
INSERT into Clubs values (476, "Parma");
INSERT into Clubs values (477, "FC Midtjylland");
INSERT into Clubs values (478, "Alanyaspor");
INSERT into Clubs values (479, "Coventry City");
INSERT into Clubs values (480, "Cracovia");
INSERT into Clubs values (481, "SC Heerenveen");
INSERT into Clubs values (482, "IF Elfsborg");
INSERT into Clubs values (483, "FC Anzhi Makhachkala");
INSERT into Clubs values (484, "Burnley");
INSERT into Clubs values (485, "Ternana");
INSERT into Clubs values (486, "Silkeborg IF");
INSERT into Clubs values (487, "SV Sandhausen");
INSERT into Clubs values (488, "SV Meppen");
INSERT into Clubs values (489, "Medicana Sivasspor");
INSERT into Clubs values (490, "Córdoba CF");
INSERT into Clubs values (491, "1. FC Köln");
INSERT into Clubs values (492, "Chemnitzer FC");
INSERT into Clubs values (493, "Newell's Old Boys");
INSERT into Clubs values (494, "Scunthorpe United");
INSERT into Clubs values (495, "Eintracht Frankfurt");
INSERT into Clubs values (496, "CF Os Belenenses");
INSERT into Clubs values (497, "FC Porto");
INSERT into Clubs values (498, "Gamba Osaka");
INSERT into Clubs values (499, "DSC Arminia Bielefeld");
INSERT into Clubs values (500, "Barnsley");
INSERT into Clubs values (501, "FC Bayern Munich");
INSERT into Clubs values (502, "AFC Wimbledon");
INSERT into Clubs values (503, "Napoli");
INSERT into Clubs values (504, "Sevilla Atlético");
INSERT into Clubs values (505, "Vitesse");
INSERT into Clubs values (506, "Juventus");
INSERT into Clubs values (507, "Stabæk Fotball");
INSERT into Clubs values (508, "New England Revolution");
INSERT into Clubs values (509, "Club León");
INSERT into Clubs values (510, "AJ Auxerre");
INSERT into Clubs values (511, "Athletic Club de Bilbao");
INSERT into Clubs values (512, "FC Schalke 04");
INSERT into Clubs values (513, "ADO Den Haag");
INSERT into Clubs values (514, "Paris FC");
INSERT into Clubs values (515, "Club Atlético Tigre");
INSERT into Clubs values (516, "Shrewsbury");
INSERT into Clubs values (517, "Pogoń Szczecin");
INSERT into Clubs values (518, "Odense Boldklub");
INSERT into Clubs values (519, "SL Benfica");
INSERT into Clubs values (520, "Independiente Medellín");
INSERT into Clubs values (521, "CPD Junior Barranquilla");
INSERT into Clubs values (522, "CD Aves");
INSERT into Clubs values (523, "Montreal Impact");
INSERT into Clubs values (524, "Aston Villa");
INSERT into Clubs values (525, "Swansea City");
INSERT into Clubs values (526, "Corporación Club Deportivo Tuluá");
INSERT into Clubs values (527, "Karlsruher SC");
INSERT into Clubs values (528, "SV Mattersburg");
INSERT into Clubs values (529, "Kalmar FF");
INSERT into Clubs values (530, "Motherwell");
INSERT into Clubs values (531, "Holstein Kiel");
INSERT into Clubs values (532, "Kristiansund BK");
INSERT into Clubs values (533, "Malmö FF");
INSERT into Clubs values (534, "Piast Gliwice");
INSERT into Clubs values (535, "Perth Glory");
INSERT into Clubs values (536, "Sport Club do Recife");
INSERT into Clubs values (537, "Sporting Lokeren");
INSERT into Clubs values (538, "KAA Gent");
INSERT into Clubs values (539, "RSC Anderlecht");
INSERT into Clubs values (540, "Unión Española");
INSERT into Clubs values (541, "Deportes Iquique");
INSERT into Clubs values (542, "SV Wehen Wiesbaden");
INSERT into Clubs values (543, "FC Nantes");
INSERT into Clubs values (544, "Bray Wanderers");
INSERT into Clubs values (545, "Wisła Płock");
INSERT into Clubs values (546, "Bahía Blanca");
INSERT into Clubs values (547, "KV Kortrijk");
INSERT into Clubs values (548, "Shakhtar Donetsk");
INSERT into Clubs values (549, "1. FSV Mainz 05");
INSERT into Clubs values (550, "C.D. Leonesa S.A.D.");
INSERT into Clubs values (551, "SV Werder Bremen");
INSERT into Clubs values (552, "Foggia");
INSERT into Clubs values (553, "Al Ahli");
INSERT into Clubs values (554, "San Lorenzo de Almagro");
INSERT into Clubs values (555, "La Berrichonne de Châteauroux");
INSERT into Clubs values (556, "Queens Park Rangers");
INSERT into Clubs values (557, "Olympique de Marseille");
INSERT into Clubs values (558, "Racing Club de Avellaneda");
INSERT into Clubs values (559, "Benevento Calcio");
INSERT into Clubs values (560, "FC Tosno");
INSERT into Clubs values (561, "Bohemian FC");
INSERT into Clubs values (562, "Bari");
INSERT into Clubs values (563, "AD Alcorcón");
INSERT into Clubs values (564, "FC Luzern");
INSERT into Clubs values (565, "Huddersfield Town");
INSERT into Clubs values (566, "Shimizu S-Pulse");
INSERT into Clubs values (567, "Girona CF");
INSERT into Clubs values (568, "Club de Deportes Temuco");
INSERT into Clubs values (569, "VVV-Venlo");
INSERT into Clubs values (570, "FC Carl Zeiss Jena");
INSERT into Clubs values (571, "Bolton Wanderers");
INSERT into Clubs values (572, "GwangJu FC");
INSERT into Clubs values (573, "West Bromwich Albion");
INSERT into Clubs values (574, "FC Red Bull Salzburg");
INSERT into Clubs values (575, "FC Sion");
INSERT into Clubs values (576, "Lyngby BK");
INSERT into Clubs values (577, "Aarhus GF");
INSERT into Clubs values (578, "Sandecja Nowy Sącz");
INSERT into Clubs values (579, "FC Sochaux-Montbéliard");
INSERT into Clubs values (580, "Ohod Club");
INSERT into Clubs values (581, "Colo-Colo");
INSERT into Clubs values (582, "Wellington Phoenix");
INSERT into Clubs values (583, "1. FC Heidenheim");
INSERT into Clubs values (584, "Lobos de la BUAP");
INSERT into Clubs values (585, "Lokomotiv Moscow");
INSERT into Clubs values (586, "Kashima Antlers");
INSERT into Clubs values (587, "LASK Linz");
INSERT into Clubs values (588, "Kayserispor");
INSERT into Clubs values (589, "Talleres de Cordoba");
INSERT into Clubs values (590, "Djurgårdens IF");
INSERT into Clubs values (591, "FC Lugano");
INSERT into Clubs values (592, "Al Taawoun");
INSERT into Clubs values (593, "FC Ingolstadt 04");
INSERT into Clubs values (594, "Chelsea");
INSERT into Clubs values (595, "D.C. United");
INSERT into Clubs values (596, "IFK Göteborg");
INSERT into Clubs values (597, "Carpi");
INSERT into Clubs values (598, "Walsall");
INSERT into Clubs values (599, "Sporting CP");
INSERT into Clubs values (600, "Girondins de Bordeaux");
INSERT into Clubs values (601, "Vissel Kobe");
INSERT into Clubs values (602, "BK Häcken");
INSERT into Clubs values (603, "Legia Warszawa");
INSERT into Clubs values (604, "Galway United");
INSERT into Clubs values (605, "GIF Sundsvall");
INSERT into Clubs values (606, "FC Nordsjælland");
INSERT into Clubs values (607, "Ascoli");
INSERT into Clubs values (608, "Kardemir Karabükspor");
INSERT into Clubs values (609, "Nîmes Olympique");
INSERT into Clubs values (610, "Kashiwa Reysol");
INSERT into Clubs values (611, "St. Johnstone FC");
INSERT into Clubs values (612, "Real Oviedo");
INSERT into Clubs values (613, "Fenerbahçe SK");
INSERT into Clubs values (614, "PEC Zwolle");
INSERT into Clubs values (615, "Club América");
INSERT into Clubs values (616, "Hansa Rostock");
INSERT into Clubs values (617, "IK Sirius");
INSERT into Clubs values (618, "Portland Timbers");
INSERT into Clubs values (619, "CS Marítimo");
INSERT into Clubs values (620, "AS Monaco");
INSERT into Clubs values (621, "Birmingham City");
INSERT into Clubs values (622, "Chacarita Juniors");
INSERT into Clubs values (623, "RB Leipzig");
INSERT into Clubs values (624, "Sparta Rotterdam");
INSERT into Clubs values (625, "Tondela");
INSERT into Clubs values (626, "SønderjyskE");
INSERT into Clubs values (627, "1. FC Magdeburg");
INSERT into Clubs values (628, "Derby County");
INSERT into Clubs values (629, "Lincoln City");
INSERT into Clubs values (630, "Boca Juniors");
INSERT into Clubs values (631, "İstanbul Başakşehir FK");
INSERT into Clubs values (632, "Monarcas Morelia");
INSERT into Clubs values (633, "Universidad de Chile");
INSERT into Clubs values (634, " SSV Jahn Regensburg");
INSERT into Clubs values (635, "Port Vale");
INSERT into Clubs values (636, "CD America de Cali");
INSERT into Clubs values (637, "Brøndby IF");
INSERT into Clubs values (638, "Panathinaikos FC");
INSERT into Clubs values (639, "UD Las Palmas");
INSERT into Clubs values (640, "Leeds United");
INSERT into Clubs values (641, "West Ham United");
INSERT into Clubs values (642, "FC Admira Wacker Mödling");
INSERT into Clubs values (643, "Sunderland");
INSERT into Clubs values (644, "FC Paços de Ferreira");
INSERT into Clubs values (645, "Sevilla FC");
INSERT into Clubs values (646, "Virtus Entella");
INSERT into Clubs values (647, "Partick Thistle F.C.");
