DROP TABLE IF EXISTS Club; 
CREATE TABLE Club (Club_id INT, Club_name VARCHAR(40));

INSERT into Club values (0, "");
INSERT into Club values (1, "FC St. Gallen");
INSERT into Club values (2, "Fleetwood Town");
INSERT into Club values (3, "St. Patrick's Athletic");
INSERT into Club values (4, "Ferrara (SPAL)");
INSERT into Club values (5, "Bologna");
INSERT into Club values (6, "Torino");
INSERT into Club values (7, "Adelaide United");
INSERT into Club values (8, "Independiente Santa Fe");
INSERT into Club values (9, "Aalborg BK");
INSERT into Club values (10, "Al Nassr");
INSERT into Club values (11, "Royal Excel Mouscron");
INSERT into Club values (12, "Le Havre AC");
INSERT into Club values (13, "Rochdale");
INSERT into Club values (14, "Borussia Mönchengladbach");
INSERT into Club values (15, "Liverpool");
INSERT into Club values (16, "Águilas Doradas");
INSERT into Club values (17, "Yeovil Town");
INSERT into Club values (18, "Real Zaragoza");
INSERT into Club values (19, "Gimnàstic de Tarragona");
INSERT into Club values (20, "Associação Atlética Ponte Preta");
INSERT into Club values (21, "Colorado Rapids");
INSERT into Club values (22, "Gimnasia y Esgrima La Plata");
INSERT into Club values (23, "Inter");
INSERT into Club values (24, "SK Rapid Wien");
INSERT into Club values (25, "Leicester City");
INSERT into Club values (26, "Bristol Rovers");
INSERT into Club values (27, "PAOK Thessaloniki");
INSERT into Club values (28, "Atletico Nacional Medellin");
INSERT into Club values (29, "Al Ittihad");
INSERT into Club values (30, "RC Strasbourg");
INSERT into Club values (31, "RC Celta de Vigo");
INSERT into Club values (32, "Halmstads BK");
INSERT into Club values (33, "Hibernian");
INSERT into Club values (34, "Club Atlético Patronato");
INSERT into Club values (35, "Sligo Rovers");
INSERT into Club values (36, "FC Twente");
INSERT into Club values (37, "Chesterfield");
INSERT into Club values (38, "Brescia");
INSERT into Club values (39, "FC Basel");
INSERT into Club values (40, "GFC Ajaccio");
INSERT into Club values (41, "Western Sydney Wanderers");
INSERT into Club values (42, "Defensa y Justicia");
INSERT into Club values (43, "Ross County FC");
INSERT into Club values (44, "Notts County");
INSERT into Club values (45, "Montpellier Hérault SC");
INSERT into Club values (46, "Sangju Sangmu FC");
INSERT into Club values (47, "Cambridge United");
INSERT into Club values (48, "SC Fortuna Köln");
INSERT into Club values (49, "Club Atlético Lanús");
INSERT into Club values (50, "Zenit St. Petersburg");
INSERT into Club values (51, "Brighton & Hove Albion");
INSERT into Club values (52, "LOSC Lille");
INSERT into Club values (53, "Rosario Central");
INSERT into Club values (54, "Sheffield Wednesday");
INSERT into Club values (55, "Club Brugge KV");
INSERT into Club values (56, "NAC Breda");
INSERT into Club values (57, "FC Lorient");
INSERT into Club values (58, "Lech Poznań");
INSERT into Club values (59, "Valencia CF");
INSERT into Club values (60, "FC Augsburg");
INSERT into Club values (61, "Kilmarnock");
INSERT into Club values (62, "Manchester City");
INSERT into Club values (63, "Asociacion Deportivo Cali");
INSERT into Club values (64, "Wolfsberger AC");
INSERT into Club values (65, "Limerick FC");
INSERT into Club values (66, "Cádiz C.F.");
INSERT into Club values (67, "Deportivo Toluca");
INSERT into Club values (68, "Hellas Verona");
INSERT into Club values (69, "Frosinone");
INSERT into Club values (70, "Olympiakos CFP");
INSERT into Club values (71, "En Avant de Guingamp");
INSERT into Club values (72, "Deportes Tolima");
INSERT into Club values (73, "Ventforet Kofu");
INSERT into Club values (74, "CD Los Millionarios Bogota");
INSERT into Club values (75, "Querétaro");
INSERT into Club values (76, "RC Lens");
INSERT into Club values (77, "Odds BK");
INSERT into Club values (78, "Swindon Town");
INSERT into Club values (79, "Atiker Konyaspor");
INSERT into Club values (80, "Vancouver Whitecaps FC");
INSERT into Club values (81, "Crotone");
INSERT into Club values (82, "Colon de Santa Fe");
INSERT into Club values (83, "Perugia");
INSERT into Club values (84, "Forest Green");
INSERT into Club values (85, "Chicago Fire Soccer Club");
INSERT into Club values (86, "Cruzeiro");
INSERT into Club values (87, "SG Sonnenhof Großaspach");
INSERT into Club values (88, "Molde FK");
INSERT into Club values (89, "Bayer 04 Leverkusen");
INSERT into Club values (90, "FC Dallas");
INSERT into Club values (91, "Tigres FC");
INSERT into Club values (92, "Sogndal");
INSERT into Club values (93, "Cremonese");
INSERT into Club values (94, "Melbourne City");
INSERT into Club values (95, "US Orléans Loiret Football");
INSERT into Club values (96, "Zagłębie Lubin");
INSERT into Club values (97, "New York City Football Club");
INSERT into Club values (98, "SC Paderborn 07");
INSERT into Club values (99, "Estoril Praia");
INSERT into Club values (100, "Argentinos Juniors");
INSERT into Club values (101, "Sportfreunde Lotte");
INSERT into Club values (102, "Fluminense Football Club");
INSERT into Club values (103, "US Quevilly-Rouen");
INSERT into Club values (104, "F.C. Tokyo");
INSERT into Club values (105, "Atlético Madrid");
INSERT into Club values (106, "Banfield");
INSERT into Club values (107, "FC Seoul");
INSERT into Club values (108, "Associação Chapecoense de Futebol");
INSERT into Club values (109, "Finn Harps");
INSERT into Club values (110, "Sheffield United");
INSERT into Club values (111, "ES Troyes AC");
INSERT into Club values (112, "Kaizer Chiefs");
INSERT into Club values (113, "Bradford City");
INSERT into Club values (114, "Botafogo de Futebol e Regatas");
INSERT into Club values (115, "Incheon United FC");
INSERT into Club values (116, "FC Ural");
INSERT into Club values (117, "Hamburger SV");
INSERT into Club values (118, "Bury");
INSERT into Club values (119, "Sparta Praha");
INSERT into Club values (120, "Minnesota Thunder");
INSERT into Club values (121, "Derry City");
INSERT into Club values (122, "FK Austria Wien");
INSERT into Club values (123, "Clube Atlético Mineiro");
INSERT into Club values (124, "Cruz Azul");
INSERT into Club values (125, "Heart of Midlothian");
INSERT into Club values (126, "Wycombe Wanderers");
INSERT into Club values (127, "KRC Genk");
INSERT into Club values (128, "Avaí Futebol Clube");
INSERT into Club values (129, "Waasland-Beveren");
INSERT into Club values (130, "Albirex Niigata");
INSERT into Club values (131, "Atlético Clube Goianiense");
INSERT into Club values (132, "Crewe Alexandra");
INSERT into Club values (133, "SpVgg Unterhaching");
INSERT into Club values (134, "Atalanta");
INSERT into Club values (135, "Dundalk");
INSERT into Club values (136, "Fulham");
INSERT into Club values (137, "Millwall");
INSERT into Club values (138, "Santos Laguna");
INSERT into Club values (139, "AIK Solna");
INSERT into Club values (140, "Universidad Católica");
INSERT into Club values (141, "Newcastle United");
INSERT into Club values (142, "IFK Norrköping");
INSERT into Club values (143, "CD Numancia");
INSERT into Club values (144, "Grupo Desportivo de Chaves");
INSERT into Club values (145, "Heracles Almelo");
INSERT into Club values (146, "Sampdoria");
INSERT into Club values (147, "SG Dynamo Dresden");
INSERT into Club values (148, "Real Salt Lake");
INSERT into Club values (149, "Unión de Santa Fe");
INSERT into Club values (150, "Patriotas Boyacá FC");
INSERT into Club values (151, "Al Hilal");
INSERT into Club values (152, "Jönköpings Södra IF");
INSERT into Club values (153, "VfB Stuttgart");
INSERT into Club values (154, "Gençlerbirliği SK");
INSERT into Club values (155, "Blackpool");
INSERT into Club values (156, "Yokohama F. Marinos");
INSERT into Club values (157, "SC Freiburg");
INSERT into Club values (158, "Feyenoord");
INSERT into Club values (159, "Genoa");
INSERT into Club values (160, "Monterrey");
INSERT into Club values (161, "FC Thun");
INSERT into Club values (162, "Aalesunds FK");
INSERT into Club values (163, "Jeju United FC");
INSERT into Club values (164, "Melbourne Victory");
INSERT into Club values (165, "Barnet");
INSERT into Club values (166, "La Spezia");
INSERT into Club values (167, "Roda JC Kerkrade");
INSERT into Club values (168, "Wisła Kraków");
INSERT into Club values (169, "Real Sociedad");
INSERT into Club values (170, "Doncaster Rovers");
INSERT into Club values (171, "Chamois Niortais FC");
INSERT into Club values (172, "La Equidad");
INSERT into Club values (173, "Granada CF");
INSERT into Club values (174, "Deportivo Pasto");
INSERT into Club values (175, "FC Lausanne-Sports");
INSERT into Club values (176, "Kasimpaşa SK");
INSERT into Club values (177, "Korona Kielce");
INSERT into Club values (178, "Strømsgodset IF");
INSERT into Club values (179, "SKN St. Pölten");
INSERT into Club values (180, "SK Sturm Graz");
INSERT into Club values (181, "Hertha BSC Berlin");
INSERT into Club values (182, "Drogheda United");
INSERT into Club values (183, "CD Huachipato");
INSERT into Club values (184, "Vålerenga Fotball");
INSERT into Club values (185, "Celtic");
INSERT into Club values (186, "AC Ajaccio");
INSERT into Club values (187, "Jagiellonia Białystok");
INSERT into Club values (188, "Sanfrecce Hiroshima");
INSERT into Club values (189, "Bournemouth");
INSERT into Club values (190, "Clermont Foot 63");
INSERT into Club values (191, "Roma");
INSERT into Club values (192, "FSV Zwickau");
INSERT into Club values (193, "AS Saint-Étienne");
INSERT into Club values (194, "AZ Alkmaar");
INSERT into Club values (195, "Charlton Athletic");
INSERT into Club values (196, "Getafe CF");
INSERT into Club values (197, "Olympique Lyonnais");
INSERT into Club values (198, "FC Erzgebirge Aue");
INSERT into Club values (199, "San Jose Earthquakes");
INSERT into Club values (200, "Milan");
INSERT into Club values (201, "Vercelli");
INSERT into Club values (202, "Levante UD");
INSERT into Club values (203, "Crawley Town");
INSERT into Club values (204, "Morecambe");
INSERT into Club values (205, "Coritiba Foot Ball Club");
INSERT into Club values (206, "Southend United");
INSERT into Club values (207, "Tromsø IL");
INSERT into Club values (208, "Daegu FC");
INSERT into Club values (209, "Guadalajara");
INSERT into Club values (210, "Górnik Zabrze");
INSERT into Club values (211, "Chievo Verona");
INSERT into Club values (212, "Atlético Tucumán");
INSERT into Club values (213, "Bristol City");
INSERT into Club values (214, "Exeter City");
INSERT into Club values (215, "Omiya Ardija");
INSERT into Club values (216, "Reading");
INSERT into Club values (217, "Grasshopper Club Zürich");
INSERT into Club values (218, "RC Deportivo de La Coruña");
INSERT into Club values (219, "AC Horsens");
INSERT into Club values (220, "VfL Osnabrück");
INSERT into Club values (221, "Júbilo Iwata");
INSERT into Club values (222, "Columbus Crew SC");
INSERT into Club values (223, "FC Barcelona B");
INSERT into Club values (224, "Hallescher FC");
INSERT into Club values (225, "Málaga CF");
INSERT into Club values (226, "River Plate");
INSERT into Club values (227, "Rayo Vallecano");
INSERT into Club values (228, "Arsenal de Sarandí");
INSERT into Club values (229, "Toronto FC");
INSERT into Club values (230, "CD Tenerife");
INSERT into Club values (231, "Cerezo Osaka");
INSERT into Club values (232, "Eintracht Braunschweig");
INSERT into Club values (233, "1. FC Union Berlin");
INSERT into Club values (234, "Rot-Weiß Erfurt");
INSERT into Club values (235, "Oldham Athletic");
INSERT into Club values (236, "Lillestrøm SK");
INSERT into Club values (237, "Moreirense FC");
INSERT into Club values (238, "Curicó Unido");
INSERT into Club values (239, "SV Zulte-Waregem");
INSERT into Club values (240, "KV Oostende");
INSERT into Club values (241, "Stoke City");
INSERT into Club values (242, "Arsenal");
INSERT into Club values (243, "Luton Town");
INSERT into Club values (244, "Stade Brestois 29");
INSERT into Club values (245, "Willem II");
INSERT into Club values (246, "FC Ufa");
INSERT into Club values (247, "CD Once Caldas Manizales");
INSERT into Club values (248, "New York Red Bulls");
INSERT into Club values (249, "Atlanta United FC");
INSERT into Club values (250, "Newcastle Jets");
INSERT into Club values (251, "Al Shabab");
INSERT into Club values (252, "Ettifaq FC");
INSERT into Club values (253, "Akhisar Belediyespor");
INSERT into Club values (254, "Al Batin");
INSERT into Club values (255, "Colchester United");
INSERT into Club values (256, "SK Brann");
INSERT into Club values (257, "FC Rostov");
INSERT into Club values (258, "Bourg en Bresse Péronnas 01");
INSERT into Club values (259, "Philadelphia Union");
INSERT into Club values (260, "Everton");
INSERT into Club values (261, "FC Helsingør");
INSERT into Club values (262, "1. FC Nürnberg");
INSERT into Club values (263, "Cork City");
INSERT into Club values (264, "Arsenal Tula");
INSERT into Club values (265, "Club Tijuana");
INSERT into Club values (266, "Palermo");
INSERT into Club values (267, "Temperley");
INSERT into Club values (268, "Ipswich Town");
INSERT into Club values (269, "VfR Aalen");
INSERT into Club values (270, "Northampton Town");
INSERT into Club values (271, "SpVgg Greuther Fürth");
INSERT into Club values (272, "Sandefjord Fotball");
INSERT into Club values (273, "Preston North End");
INSERT into Club values (274, "SD Huesca");
INSERT into Club values (275, "BSC Young Boys");
INSERT into Club values (276, "Tottenham Hotspur");
INSERT into Club values (277, "Evkur Yeni Malatyaspor");
INSERT into Club values (278, "F.B.C. Unione Venezia");
INSERT into Club values (279, "Empoli");
INSERT into Club values (280, "Dundee FC");
INSERT into Club values (281, "U.N.A.M.");
INSERT into Club values (282, "Rosenborg BK");
INSERT into Club values (283, "Santos Futebol Clube");
INSERT into Club values (284, "MSV Duisburg");
INSERT into Club values (285, "Al Fayha");
INSERT into Club values (286, "Vitória Setúbal");
INSERT into Club values (287, "CD Leganés");
INSERT into Club values (288, "Suwon Samsung Bluewings");
INSERT into Club values (289, "Brisbane Roar");
INSERT into Club values (290, "FC København");
INSERT into Club values (291, "Real Sporting de Gijón");
INSERT into Club values (292, "Bursaspor");
INSERT into Club values (293, "Göztepe");
INSERT into Club values (294, "Amiens SC Football");
INSERT into Club values (295, "Pachuca");
INSERT into Club values (296, "Burton Albion");
INSERT into Club values (297, "Amkar Perm");
INSERT into Club values (298, "Vegalta Sendai");
INSERT into Club values (299, "1. FC Kaiserslautern");
INSERT into Club values (300, "Carlisle United");
INSERT into Club values (301, "Boavista FC");
INSERT into Club values (302, "Shamrock Rovers");
INSERT into Club values (303, "UD Almería");
INSERT into Club values (304, "Milton Keynes Dons");
INSERT into Club values (305, "Puebla");
INSERT into Club values (306, "Randers FC");
INSERT into Club values (307, "Östersunds FK");
INSERT into Club values (308, "Everton de Viña del Mar");
INSERT into Club values (309, "Atlético Huila");
INSERT into Club values (310, "FC Groningen");
INSERT into Club values (311, "Wigan Athletic");
INSERT into Club values (312, "Vélez Sarsfield");
INSERT into Club values (313, "CD Feirense");
INSERT into Club values (314, "FC St. Pauli");
INSERT into Club values (315, "Grimsby Town");
INSERT into Club values (316, "Deportivo Alavés");
INSERT into Club values (317, "AS Nancy Lorraine");
INSERT into Club values (318, "Blackburn Rovers");
INSERT into Club values (319, "Sporting Kansas City");
INSERT into Club values (320, "Portimonense SC");
INSERT into Club values (321, "SD Eibar");
INSERT into Club values (322, "CA Osasuna");
INSERT into Club values (323, "Necaxa");
INSERT into Club values (324, "Kawasaki Frontale");
INSERT into Club values (325, "Sassuolo");
INSERT into Club values (326, "Paris Saint-Germain");
INSERT into Club values (327, "Rangers");
INSERT into Club values (328, "Rotherham United");
INSERT into Club values (329, "Sint-Truidense VV");
INSERT into Club values (330, "RCD Espanyol");
INSERT into Club values (331, "Udinese");
INSERT into Club values (332, "FC Barcelona");
INSERT into Club values (333, "Novara");
INSERT into Club values (334, "Plymouth Argyle");
INSERT into Club values (335, "Avellino");
INSERT into Club values (336, "Sydney FC");
INSERT into Club values (337, "CD Antofagasta");
INSERT into Club values (338, "Villarreal CF");
INSERT into Club values (339, "Pohang Steelers");
INSERT into Club values (340, "Fiorentina");
INSERT into Club values (341, "Dinamo Moscow");
INSERT into Club values (342, "Lazio");
INSERT into Club values (343, "Mansfield Town");
INSERT into Club values (344, "Hannover 96");
INSERT into Club values (345, "Tours FC");
INSERT into Club values (346, "FC Krasnodar");
INSERT into Club values (347, "Oxford United");
INSERT into Club values (348, "Clube Atlético Paranaense");
INSERT into Club values (349, "Real Madrid CF");
INSERT into Club values (350, "Gangwon FC");
INSERT into Club values (351, "Cittadella");
INSERT into Club values (352, "Lorca Deportiva CF");
INSERT into Club values (353, "Fortuna Düsseldorf");
INSERT into Club values (354, "CF Reus Deportiu");
INSERT into Club values (355, "Urawa Red Diamonds");
INSERT into Club values (356, "Orlando City Soccer Club");
INSERT into Club values (357, "Pescara");
INSERT into Club values (358, "Crystal Palace");
INSERT into Club values (359, "Antalyaspor");
INSERT into Club values (360, "Seattle Sounders FC");
INSERT into Club values (361, "Tiburones Rojos de Veracruz");
INSERT into Club values (362, "Stevenage");
INSERT into Club values (363, "FC Utrecht");
INSERT into Club values (364, "Godoy Cruz");
INSERT into Club values (365, "Audax Italiano");
INSERT into Club values (366, "Manchester United");
INSERT into Club values (367, "Sporting Charleroi");
INSERT into Club values (368, "Nottingham Forest");
INSERT into Club values (369, "Valenciennes FC");
INSERT into Club values (370, "Central Coast Mariners");
INSERT into Club values (371, "Peterborough United");
INSERT into Club values (372, "Royal Antwerp FC");
INSERT into Club values (373, "Estudiantes de La Plata");
INSERT into Club values (374, "Salernitana");
INSERT into Club values (375, "KAS Eupen");
INSERT into Club values (376, "Hammarby IF");
INSERT into Club values (377, "Dijon FCO");
INSERT into Club values (378, "Envigado FC");
INSERT into Club values (379, "Real Betis Balompié");
INSERT into Club values (380, "Atlético Bucaramanga");
INSERT into Club values (381, "SCR Altach");
INSERT into Club values (382, "San Luis de Quillota");
INSERT into Club values (383, "Santiago Wanderers");
INSERT into Club values (384, "SC Preußen Münster");
INSERT into Club values (385, "Southampton");
INSERT into Club values (386, "Vitória Guimarães");
INSERT into Club values (387, "Cheltenham Town");
INSERT into Club values (388, "KV Mechelen");
INSERT into Club values (389, "Rio Ave FC");
INSERT into Club values (390, "Vitória ");
INSERT into Club values (391, "FK Haugesund");
INSERT into Club values (392, "Terek Grozny");
INSERT into Club values (393, "Portsmouth");
INSERT into Club values (394, "SC Braga");
INSERT into Club values (395, "Middlesbrough");
INSERT into Club values (396, "Watford");
INSERT into Club values (397, "Toulouse FC");
INSERT into Club values (398, "CD Lugo");
INSERT into Club values (399, "PSV");
INSERT into Club values (400, "Jeonnam Dragons");
INSERT into Club values (401, "Gillingham");
INSERT into Club values (402, "CD Universidad de Concepción");
INSERT into Club values (403, "AFC Eskilstuna");
INSERT into Club values (404, "SM Caen");
INSERT into Club values (405, "Lechia Gdańsk");
INSERT into Club values (406, "Cardiff City");
INSERT into Club values (407, "Angers SCO");
INSERT into Club values (408, "OGC Nice");
INSERT into Club values (409, "VfL Wolfsburg");
INSERT into Club values (410, "Sarpsborg 08 FF");
INSERT into Club values (411, "Stade de Reims");
INSERT into Club values (412, "Śląsk Wrocław");
INSERT into Club values (413, "Grêmio Foot-Ball Porto Alegrense");
INSERT into Club values (414, "Jeonbuk Hyundai Motors");
INSERT into Club values (415, "Ajax");
INSERT into Club values (416, "Werder Bremen II");
INSERT into Club values (417, "Cagliari");
INSERT into Club values (418, "SV Darmstadt 98");
INSERT into Club values (419, "Örebro SK");
INSERT into Club values (420, "Club Atlas");
INSERT into Club values (421, "Hamilton Academical FC");
INSERT into Club values (422, "Arka Gdynia");
INSERT into Club values (423, "Brentford");
INSERT into Club values (424, "Hobro IK");
INSERT into Club values (425, "Hokkaido Consadole Sapporo");
INSERT into Club values (426, "HJK Helsinki");
INSERT into Club values (427, "VfL Bochum");
INSERT into Club values (428, "Real Valladolid");
INSERT into Club values (429, "Tigres U.A.N.L.");
INSERT into Club values (430, "FC Metz");
INSERT into Club values (431, "Accrington Stanley");
INSERT into Club values (432, "Al Faisaly");
INSERT into Club values (433, "São Paulo Futebol Clube");
INSERT into Club values (434, "Trabzonspor");
INSERT into Club values (435, "Galatasaray SK");
INSERT into Club values (436, "CD Palestino");
INSERT into Club values (437, "FC SKA-Energiya Khabarovsk");
INSERT into Club values (438, "Houston Dynamo");
INSERT into Club values (439, "AEK Athens");
INSERT into Club values (440, "LA Galaxy");
INSERT into Club values (441, "FC Zürich");
INSERT into Club values (442, "Jaguares Fútbol Club");
INSERT into Club values (443, "Independiente");
INSERT into Club values (444, "Rubin Kazan");
INSERT into Club values (445, "Ulsan Hyundai Horang-i");
INSERT into Club values (446, "Sociedade Esportiva Palmeiras");
INSERT into Club values (447, "Stade Rennais FC");
INSERT into Club values (448, "Beşiktaş JK");
INSERT into Club values (449, "Spartak Moscow");
INSERT into Club values (450, "Osmanlıspor");
INSERT into Club values (451, "Al Raed");
INSERT into Club values (452, "Borussia Dortmund");
INSERT into Club values (453, "Termalica Bruk-Bet Nieciecza");
INSERT into Club values (454, "Standard de Liège");
INSERT into Club values (455, "Cesena");
INSERT into Club values (456, "Excelsior");
INSERT into Club values (457, "San Martín de San Juan");
INSERT into Club values (458, "Wolverhampton Wanderers");
INSERT into Club values (459, "Newport County");
INSERT into Club values (460, "Würzburger FV");
INSERT into Club values (461, "Belgrano de Córdoba");
INSERT into Club values (462, "CSKA Moscow");
INSERT into Club values (463, "TSG 1899 Hoffenheim");
INSERT into Club values (464, "Norwich City");
INSERT into Club values (465, "Sagan Tosu");
INSERT into Club values (466, "Orlando Pirates");
INSERT into Club values (467, "Hull City");
INSERT into Club values (468, "Al Qadisiyah");
INSERT into Club values (469, "Viking FK");
INSERT into Club values (470, "CD O'Higgins");
INSERT into Club values (471, "Al Fateh");
INSERT into Club values (472, "Club Atlético Huracán");
INSERT into Club values (473, "Alianza Petrolera");
INSERT into Club values (474, "Aberdeen");
INSERT into Club values (475, "Albacete Balompié");
INSERT into Club values (476, "Parma");
INSERT into Club values (477, "FC Midtjylland");
INSERT into Club values (478, "Alanyaspor");
INSERT into Club values (479, "Coventry City");
INSERT into Club values (480, "Cracovia");
INSERT into Club values (481, "SC Heerenveen");
INSERT into Club values (482, "IF Elfsborg");
INSERT into Club values (483, "FC Anzhi Makhachkala");
INSERT into Club values (484, "Burnley");
INSERT into Club values (485, "Ternana");
INSERT into Club values (486, "Silkeborg IF");
INSERT into Club values (487, "SV Sandhausen");
INSERT into Club values (488, "SV Meppen");
INSERT into Club values (489, "Medicana Sivasspor");
INSERT into Club values (490, "Córdoba CF");
INSERT into Club values (491, "1. FC Köln");
INSERT into Club values (492, "Chemnitzer FC");
INSERT into Club values (493, "Newell's Old Boys");
INSERT into Club values (494, "Scunthorpe United");
INSERT into Club values (495, "Eintracht Frankfurt");
INSERT into Club values (496, "CF Os Belenenses");
INSERT into Club values (497, "FC Porto");
INSERT into Club values (498, "Gamba Osaka");
INSERT into Club values (499, "DSC Arminia Bielefeld");
INSERT into Club values (500, "Barnsley");
INSERT into Club values (501, "FC Bayern Munich");
INSERT into Club values (502, "AFC Wimbledon");
INSERT into Club values (503, "Napoli");
INSERT into Club values (504, "Sevilla Atlético");
INSERT into Club values (505, "Vitesse");
INSERT into Club values (506, "Juventus");
INSERT into Club values (507, "Stabæk Fotball");
INSERT into Club values (508, "New England Revolution");
INSERT into Club values (509, "Club León");
INSERT into Club values (510, "AJ Auxerre");
INSERT into Club values (511, "Athletic Club de Bilbao");
INSERT into Club values (512, "FC Schalke 04");
INSERT into Club values (513, "ADO Den Haag");
INSERT into Club values (514, "Paris FC");
INSERT into Club values (515, "Club Atlético Tigre");
INSERT into Club values (516, "Shrewsbury");
INSERT into Club values (517, "Pogoń Szczecin");
INSERT into Club values (518, "Odense Boldklub");
INSERT into Club values (519, "SL Benfica");
INSERT into Club values (520, "Independiente Medellín");
INSERT into Club values (521, "CPD Junior Barranquilla");
INSERT into Club values (522, "CD Aves");
INSERT into Club values (523, "Montreal Impact");
INSERT into Club values (524, "Aston Villa");
INSERT into Club values (525, "Swansea City");
INSERT into Club values (526, "Corporación Club Deportivo Tuluá");
INSERT into Club values (527, "Karlsruher SC");
INSERT into Club values (528, "SV Mattersburg");
INSERT into Club values (529, "Kalmar FF");
INSERT into Club values (530, "Motherwell");
INSERT into Club values (531, "Holstein Kiel");
INSERT into Club values (532, "Kristiansund BK");
INSERT into Club values (533, "Malmö FF");
INSERT into Club values (534, "Piast Gliwice");
INSERT into Club values (535, "Perth Glory");
INSERT into Club values (536, "Sport Club do Recife");
INSERT into Club values (537, "Sporting Lokeren");
INSERT into Club values (538, "KAA Gent");
INSERT into Club values (539, "RSC Anderlecht");
INSERT into Club values (540, "Unión Española");
INSERT into Club values (541, "Deportes Iquique");
INSERT into Club values (542, "SV Wehen Wiesbaden");
INSERT into Club values (543, "FC Nantes");
INSERT into Club values (544, "Bray Wanderers");
INSERT into Club values (545, "Wisła Płock");
INSERT into Club values (546, "Bahía Blanca");
INSERT into Club values (547, "KV Kortrijk");
INSERT into Club values (548, "Shakhtar Donetsk");
INSERT into Club values (549, "1. FSV Mainz 05");
INSERT into Club values (550, "C.D. Leonesa S.A.D.");
INSERT into Club values (551, "SV Werder Bremen");
INSERT into Club values (552, "Foggia");
INSERT into Club values (553, "Al Ahli");
INSERT into Club values (554, "San Lorenzo de Almagro");
INSERT into Club values (555, "La Berrichonne de Châteauroux");
INSERT into Club values (556, "Queens Park Rangers");
INSERT into Club values (557, "Olympique de Marseille");
INSERT into Club values (558, "Racing Club de Avellaneda");
INSERT into Club values (559, "Benevento Calcio");
INSERT into Club values (560, "FC Tosno");
INSERT into Club values (561, "Bohemian FC");
INSERT into Club values (562, "Bari");
INSERT into Club values (563, "AD Alcorcón");
INSERT into Club values (564, "FC Luzern");
INSERT into Club values (565, "Huddersfield Town");
INSERT into Club values (566, "Shimizu S-Pulse");
INSERT into Club values (567, "Girona CF");
INSERT into Club values (568, "Club de Deportes Temuco");
INSERT into Club values (569, "VVV-Venlo");
INSERT into Club values (570, "FC Carl Zeiss Jena");
INSERT into Club values (571, "Bolton Wanderers");
INSERT into Club values (572, "GwangJu FC");
INSERT into Club values (573, "West Bromwich Albion");
INSERT into Club values (574, "FC Red Bull Salzburg");
INSERT into Club values (575, "FC Sion");
INSERT into Club values (576, "Lyngby BK");
INSERT into Club values (577, "Aarhus GF");
INSERT into Club values (578, "Sandecja Nowy Sącz");
INSERT into Club values (579, "FC Sochaux-Montbéliard");
INSERT into Club values (580, "Ohod Club");
INSERT into Club values (581, "Colo-Colo");
INSERT into Club values (582, "Wellington Phoenix");
INSERT into Club values (583, "1. FC Heidenheim");
INSERT into Club values (584, "Lobos de la BUAP");
INSERT into Club values (585, "Lokomotiv Moscow");
INSERT into Club values (586, "Kashima Antlers");
INSERT into Club values (587, "LASK Linz");
INSERT into Club values (588, "Kayserispor");
INSERT into Club values (589, "Talleres de Cordoba");
INSERT into Club values (590, "Djurgårdens IF");
INSERT into Club values (591, "FC Lugano");
INSERT into Club values (592, "Al Taawoun");
INSERT into Club values (593, "FC Ingolstadt 04");
INSERT into Club values (594, "Chelsea");
INSERT into Club values (595, "D.C. United");
INSERT into Club values (596, "IFK Göteborg");
INSERT into Club values (597, "Carpi");
INSERT into Club values (598, "Walsall");
INSERT into Club values (599, "Sporting CP");
INSERT into Club values (600, "Girondins de Bordeaux");
INSERT into Club values (601, "Vissel Kobe");
INSERT into Club values (602, "BK Häcken");
INSERT into Club values (603, "Legia Warszawa");
INSERT into Club values (604, "Galway United");
INSERT into Club values (605, "GIF Sundsvall");
INSERT into Club values (606, "FC Nordsjælland");
INSERT into Club values (607, "Ascoli");
INSERT into Club values (608, "Kardemir Karabükspor");
INSERT into Club values (609, "Nîmes Olympique");
INSERT into Club values (610, "Kashiwa Reysol");
INSERT into Club values (611, "St. Johnstone FC");
INSERT into Club values (612, "Real Oviedo");
INSERT into Club values (613, "Fenerbahçe SK");
INSERT into Club values (614, "PEC Zwolle");
INSERT into Club values (615, "Club América");
INSERT into Club values (616, "Hansa Rostock");
INSERT into Club values (617, "IK Sirius");
INSERT into Club values (618, "Portland Timbers");
INSERT into Club values (619, "CS Marítimo");
INSERT into Club values (620, "AS Monaco");
INSERT into Club values (621, "Birmingham City");
INSERT into Club values (622, "Chacarita Juniors");
INSERT into Club values (623, "RB Leipzig");
INSERT into Club values (624, "Sparta Rotterdam");
INSERT into Club values (625, "Tondela");
INSERT into Club values (626, "SønderjyskE");
INSERT into Club values (627, "1. FC Magdeburg");
INSERT into Club values (628, "Derby County");
INSERT into Club values (629, "Lincoln City");
INSERT into Club values (630, "Boca Juniors");
INSERT into Club values (631, "İstanbul Başakşehir FK");
INSERT into Club values (632, "Monarcas Morelia");
INSERT into Club values (633, "Universidad de Chile");
INSERT into Club values (634, " SSV Jahn Regensburg");
INSERT into Club values (635, "Port Vale");
INSERT into Club values (636, "CD America de Cali");
INSERT into Club values (637, "Brøndby IF");
INSERT into Club values (638, "Panathinaikos FC");
INSERT into Club values (639, "UD Las Palmas");
INSERT into Club values (640, "Leeds United");
INSERT into Club values (641, "West Ham United");
INSERT into Club values (642, "FC Admira Wacker Mödling");
INSERT into Club values (643, "Sunderland");
INSERT into Club values (644, "FC Paços de Ferreira");
INSERT into Club values (645, "Sevilla FC");
INSERT into Club values (646, "Virtus Entella");
INSERT into Club values (647, "Partick Thistle F.C.");
