DROP TABLE IF EXISTS Country; 
CREATE TABLE Country (NTC VARCHAR(3), Country_Name VARCHAR(20), Capital VARCHAR(20), Continent VARCHAR(2), Development VARCHAR(20), Sub_region VARCHAR(35));

INSERT into Country values ("AFG", "Afghanistan", "Kabul", "AS", "Developing", "Southern Asia");
INSERT into Country values ("ALB", "Albania", "Tirana", "EU", "Developed", "Southern Europe");
INSERT into Country values ("ALG", "Algeria", "Algiers", "AF", "Developing", "Northern Africa");
INSERT into Country values ("ANG", "Angola", "Luanda", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("ATG", "Antigua & Barbuda", "St. John's", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("ARG", "Argentina", "Buenos Aires", "SA", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("ARM", "Armenia", "Yerevan", "AS", "Developing", "Western Asia");
INSERT into Country values ("AUS", "Australia", "Canberra", "OC", "Developed", "Australia and New Zealand");
INSERT into Country values ("AUT", "Austria", "Vienna", "EU", "Developed", "Western Europe");
INSERT into Country values ("AZE", "Azerbaijan", "Baku", "AS", "Developing", "Western Asia");
INSERT into Country values ("BRB", "Barbados", "Bridgetown", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("BLR", "Belarus", "Minsk", "EU", "Developed", "Eastern Europe");
INSERT into Country values ("BEL", "Belgium", "Brussels", "EU", "Developed", "Western Europe");
INSERT into Country values ("BLZ", "Belize", "Belmopan", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("BEN", "Benin", "Porto-Novo", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("BER", "Bermuda", "Hamilton", "nan", "Developed", "Northern America");
INSERT into Country values ("BOL", "Bolivia", "Sucre", "SA", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("BIH", "Bosnia Herzegovina", "Sarajevo", "EU", "Developed", "Southern Europe");
INSERT into Country values ("BRA", "Brazil", "Brasilia", "SA", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("BRU", "Brunei Darussalam", "Bandar Seri Begawan", "AS", "Developing", "South-eastern Asia");
INSERT into Country values ("BUL", "Bulgaria", "Sofia", "EU", "Developed", "Eastern Europe");
INSERT into Country values ("BFA", "Burkina Faso", "Ouagadougou", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("BDI", "Burundi", "Bujumbura", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("CMR", "Cameroon", "Yaounde", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("CAN", "Canada", "Ottawa", "nan", "Developed", "Northern America");
INSERT into Country values ("CPV", "Cape Verde", "Praia", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("CTA", "Central African Rep.", "Bangui", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("CHA", "Chad", "N'Djamena", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("CHI", "Chile", "Santiago", "SA", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("CHN", "China PR", "Beijing", "AS", "Developing", "Eastern Asia");
INSERT into Country values ("COL", "Colombia", "Bogota", "SA", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("COM", "Comoros", "Moroni", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("CGO", "Congo", "Brazzaville", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("CRC", "Costa Rica", "San Jose", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("CRO", "Croatia", "Zagreb", "EU", "Developed", "Southern Europe");
INSERT into Country values ("CUB", "Cuba", "Havana", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("CUW", "Curacao", " Willemstad", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("CYP", "Cyprus", "Nicosia", "EU", "Developing", "Western Asia");
INSERT into Country values ("CZE", "Czech Republic", "Prague", "EU", "Developed", "Eastern Europe");
INSERT into Country values ("COD", "DR Congo", "Kinshasa", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("DEN", "Denmark", "Copenhagen", "EU", "Developed", "Northern Europe");
INSERT into Country values ("DOM", "Dominican Republic", "Santo Domingo", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("ECU", "Ecuador", "Quito", "SA", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("EGY", "Egypt", "Cairo", "AF", "Developing", "Northern Africa");
INSERT into Country values ("SLV", "El Salvador", "San Salvador", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("ENG", "England", "London", "EU", "Developed", "Northern Europe");
INSERT into Country values ("EQG", "Equatorial Guinea", "Malabo", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("ERI", "Eritrea", "Asmara", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("EST", "Estonia", "Tallinn", "EU", "Developed", "Northern Europe");
INSERT into Country values ("ETH", "Ethiopia", "Addis Ababa", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("MKD", "FYR Macedonia", "Skopje", "EU", "Developed", "Southern Europe");
INSERT into Country values ("FRO", "Faroe Islands", "Torshavn", "EU", "Developed", "Northern Europe");
INSERT into Country values ("FIJ", "Fiji", "Suva", "OC", "Developing", "Melanesia");
INSERT into Country values ("FIN", "Finland", "Helsinki", "EU", "Developed", "Northern Europe");
INSERT into Country values ("FRA", "France", "Paris", "EU", "Developed", "Western Europe");
INSERT into Country values ("GAB", "Gabon", "Libreville", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("GAM", "Gambia", "Banjul", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("GEO", "Georgia", "Tbilisi", "AS", "Developing", "Western Asia");
INSERT into Country values ("GER", "Germany", "Berlin", "EU", "Developed", "Western Europe");
INSERT into Country values ("GHA", "Ghana", "Accra", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("GBZ", "Gibraltar", "Gibraltar", "EU", "Developed", "Southern Europe");
INSERT into Country values ("GRE", "Greece", "Athens", "EU", "Developed", "Southern Europe");
INSERT into Country values ("GRN", "Grenada", "St. George's", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("GUM", "Guam", "Hagatna", "OC", "Developing", "Micronesia");
INSERT into Country values ("GUA", "Guatemala", "Guatemala City", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("GUI", "Guinea", "Conakry", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("GNB", "Guinea Bissau", "Bissau", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("GUY", "Guyana", "Georgetown", "SA", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("HAI", "Haiti", "Port-au-Prince", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("HON", "Honduras", "Tegucigalpa", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("HKG", "Hong Kong", "Hong Kong", "AS", "Developing", "Eastern Asia");
INSERT into Country values ("HUN", "Hungary", "Budapest", "EU", "Developed", "Eastern Europe");
INSERT into Country values ("ISL", "Iceland", "Reykjavik", "EU", "Developed", "Northern Europe");
INSERT into Country values ("IND", "India", "New Delhi", "AS", "Developing", "Southern Asia");
INSERT into Country values ("IRN", "Iran", "Tehran", "AS", "Developing", "Southern Asia");
INSERT into Country values ("IRQ", "Iraq", "Baghdad", "AS", "Developing", "Western Asia");
INSERT into Country values ("ISR", "Israel", "Jerusalem", "AS", "Developing", "Western Asia");
INSERT into Country values ("ITA", "Italy", "Rome", "EU", "Developed", "Southern Europe");
INSERT into Country values ("CIV", "Ivory Coast", "Yamoussoukro", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("JAM", "Jamaica", "Kingston", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("JPN", "Japan", "Tokyo", "AS", "Developed", "Eastern Asia");
INSERT into Country values ("KAZ", "Kazakhstan", "Astana", "AS", "Developing", "Central Asia");
INSERT into Country values ("KEN", "Kenya", "Nairobi", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("PRK", "Korea DPR", "Pyongyang", "AS", "Developing", "Eastern Asia");
INSERT into Country values ("KOR", "Korea Republic", "Seoul", "AS", "Developing", "Eastern Asia");
INSERT into Country values ("RKS", "Kosovo", "Pristina", "EU", "Developing", "Southern Europe");
INSERT into Country values ("KUW", "Kuwait", "Kuwait City", "AS", "Developing", "Western Asia");
INSERT into Country values ("KGZ", "Kyrgyzstan", "Bishkek", "AS", "Developing", "Central Asia");
INSERT into Country values ("LVA", "Latvia", "Riga", "EU", "Developed", "Northern Europe");
INSERT into Country values ("LIB", "Lebanon", "Beirut", "AS", "Developing", "Western Asia");
INSERT into Country values ("LBR", "Liberia", "Monrovia", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("LBY", "Libya", "Tripoli", "AF", "Developing", "Northern Africa");
INSERT into Country values ("LIE", "Liechtenstein", "Vaduz", "EU", "Developed", "Western Europe");
INSERT into Country values ("LTU", "Lithuania", "Vilnius", "EU", "Developed", "Northern Europe");
INSERT into Country values ("LUX", "Luxembourg", "Luxembourg", "EU", "Developed", "Western Europe");
INSERT into Country values ("MAD", "Madagascar", "Antananarivo", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("MLI", "Mali", "Bamako", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("MLT", "Malta", "Valletta", "EU", "Developed", "Southern Europe");
INSERT into Country values ("MTN", "Mauritania", "Nouakchott", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("MRI", "Mauritius", "Port Louis", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("MEX", "Mexico", "Mexico City", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("MDA", "Moldova", "Chisinau", "EU", "Developed", "Eastern Europe");
INSERT into Country values ("MNE", "Montenegro", "Podgorica", "EU", "Developed", "Southern Europe");
INSERT into Country values ("MSR", "Montserrat", "Plymouth", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("MAR", "Morocco", "Rabat", "AF", "Developing", "Northern Africa");
INSERT into Country values ("MOZ", "Mozambique", "Maputo", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("NAM", "Namibia", "Windhoek", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("NED", "Netherlands", "Amsterdam", "EU", "Developed", "Western Europe");
INSERT into Country values ("NCL", "New Caledonia", "Noumea", "OC", "Developing", "Melanesia");
INSERT into Country values ("NZL", "New Zealand", "Wellington", "OC", "Developed", "Australia and New Zealand");
INSERT into Country values ("NIG", "Niger", "Niamey", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("NGA", "Nigeria", "Abuja", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("NIR", "Northern Ireland", "Belfast", "EU", "Developed", "Northern Europe");
INSERT into Country values ("NOR", "Norway", "Oslo", "EU", "Developed", "Northern Europe");
INSERT into Country values ("OMA", "Oman", "Muscat", "AS", "Developing", "Western Asia");
INSERT into Country values ("PLE", "Palestine", "East Jerusalem", "AS", "Developing", "Western Asia");
INSERT into Country values ("PAN", "Panama", "Panama City", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("PAR", "Paraguay", "Asuncion", "SA", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("PER", "Peru", "Lima", "SA", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("PHI", "Philippines", "Manila", "AS", "Developing", "South-eastern Asia");
INSERT into Country values ("POL", "Poland", "Warsaw", "EU", "Developed", "Eastern Europe");
INSERT into Country values ("POR", "Portugal", "Lisbon", "EU", "Developed", "Southern Europe");
INSERT into Country values ("PUR", "Puerto Rico", "San Juan", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("QAT", "Qatar", "Doha", "AS", "Developing", "Western Asia");
INSERT into Country values ("IRL", "Republic of Ireland", "Dublin", "EU", "Developed", "Northern Europe");
INSERT into Country values ("ROU", "Romania", "Bucharest", "EU", "Developed", "Eastern Europe");
INSERT into Country values ("RUS", "Russia", "Moscow", "EU", "Developed", "Eastern Europe");
INSERT into Country values ("SMR", "San Marino", "San Marino", "EU", "Developed", "Southern Europe");
INSERT into Country values ("KSA", "Saudi Arabia", "Riyadh", "AS", "Developing", "Western Asia");
INSERT into Country values ("SCT", "Scotland", "Edinburgh", "EU", "Developed", "Northern Europe");
INSERT into Country values ("SEN", "Senegal", "Dakar", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("SRB", "Serbia", "Belgrade", "EU", "Developed", "Southern Europe");
INSERT into Country values ("SLE", "Sierra Leone", "Freetown", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("SVK", "Slovakia", "Bratislava", "EU", "Developed", "Eastern Europe");
INSERT into Country values ("SVN", "Slovenia", "Ljubljana", "EU", "Developed", "Southern Europe");
INSERT into Country values ("SOM", "Somalia", "Mogadishu", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("RSA", "South Africa", "Pretoria", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("ESP", "Spain", "Madrid", "EU", "Developed", "Southern Europe");
INSERT into Country values ("SRI", "Sri Lanka", "Colombo", "AS", "Developing", "Southern Asia");
INSERT into Country values ("SKN", "St Kitts Nevis", "Basseterre", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("LCA", "St Lucia", "Castries", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("SUD", "Sudan", "Khartoum", "AF", "Developing", "Northern Africa");
INSERT into Country values ("SUR", "Suriname", "Paramaribo", "SA", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("SWZ", "Swaziland", "Mbabane", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("SWE", "Sweden", "Stockholm", "EU", "Developed", "Northern Europe");
INSERT into Country values ("SUI", "Switzerland", "Bern", "EU", "Developed", "Western Europe");
INSERT into Country values ("SYR", "Syria", "Damascus", "AS", "Developing", "Western Asia");
INSERT into Country values ("STP", "São Tomé & Príncipe", "Sao Tome", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("TAN", "Tanzania", "Dodoma", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("THA", "Thailand", "Bangkok", "AS", "Developing", "South-eastern Asia");
INSERT into Country values ("TOG", "Togo", "Lome", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("TRI", "Trinidad & Tobago", "Port of Spain", "nan", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("TUN", "Tunisia", "Tunis", "AF", "Developing", "Northern Africa");
INSERT into Country values ("TUR", "Turkey", "Ankara", "AS", "Developing", "Western Asia");
INSERT into Country values ("TKM", "Turkmenistan", "Ashgabat", "AS", "Developing", "Central Asia");
INSERT into Country values ("UGA", "Uganda", "Kampala", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("UKR", "Ukraine", "Kiev", "EU", "Developed", "Eastern Europe");
INSERT into Country values ("USA", "United States", "Washington", "nan", "Developed", "Northern America");
INSERT into Country values ("URU", "Uruguay", "Montevideo", "SA", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("UZB", "Uzbekistan", "Tashkent", "AS", "Developing", "Central Asia");
INSERT into Country values ("VEN", "Venezuela", "Caracas", "SA", "Developing", "Latin America and the Caribbean");
INSERT into Country values ("VIE", "Vietnam", "Hanoi", "AS", "Developing", "South-eastern Asia");
INSERT into Country values ("WAL", "Wales", "Cardiff", "EU", "Developed", "Northern Europe");
INSERT into Country values ("ZAM", "Zambia", "Lusaka", "AF", "Developing", "Sub-Saharan Africa");
INSERT into Country values ("ZIM", "Zimbabwe", "Harare", "AF", "Developing", "Sub-Saharan Africa");
