DROP TABLE IF EXISTS Positions;
CREATE TABLE Positions (Position_Abv VARCHAR(4), Position_Name VARCHAR(25));
INSERT INTO Positions values ("CAM", "Center_Attacking_Midfield");
INSERT INTO Positions values ("CB", "Center_Back");
INSERT INTO Positions values ("CDM", "Center_Defensive_Midfield");
INSERT INTO Positions values ("CF", "Center_Forward");
INSERT INTO Positions values ("CM", "Center_Midfield");
INSERT INTO Positions values ("LAM", "Left_Attacking_Midfield");
INSERT INTO Positions values ("LB", "Left_Back");
INSERT INTO Positions values ("LCB", "Left_Center_Back");
INSERT INTO Positions values ("LCM", "Left_Center_Midfield");
INSERT INTO Positions values ("LDM", "Left_Defensive_Midfield");
INSERT INTO Positions values ("LF", "Left_Forward");
INSERT INTO Positions values ("LM", "Left_Midfielder");
INSERT INTO Positions values ("LS", "Left_Striker");
INSERT INTO Positions values ("LW", "Left_Wing");
INSERT INTO Positions values ("LWB", "Left_Wing_Back");
INSERT INTO Positions values ("RAM", "Right_Attacking_Midfield");
INSERT INTO Positions values ("RB", "Right_Back");
INSERT INTO Positions values ("RCB", "Right_Center_Back");
INSERT INTO Positions values ("RCM", "Right_Center_Midfield");
INSERT INTO Positions values ("RDM", "Right_Defensive_Midfield");
INSERT INTO Positions values ("RF", "Right_Foward");
INSERT INTO Positions values ("RM", "Right_Midfield");
INSERT INTO Positions values ("RS", "Right_Striker");
INSERT INTO Positions values ("RW", "Right_Wing");
INSERT INTO Positions values ("RWB", "Right_Wing_Back");
INSERT INTO Positions values ("ST", "Striker");