DROP TABLE IF EXISTS Country; 
CREATE TABLE Country (Country_Code VARCHAR(5), Country_Name VARCHAR(80), Capital VARCHAR(30), Development VARCHAR(20), Sub_Region VARCHAR(80), Continent VARCHAR(20));

INSERT into Country values ("TPE", "nan", "Taipei", "nan", "nan", "AS");
INSERT into Country values ("AFG", "Afghanistan", "Kabul", "Developing", "Southern Asia", "AS");
INSERT into Country values ("ALB", "Albania", "Tirana", "Developed", "Southern Europe", "EU");
INSERT into Country values ("ALG", "Algeria", "Algiers", "Developing", "Northern Africa", "AF");
INSERT into Country values ("ASA", "American Samoa", "Pago Pago", "Developing", "Polynesia", "OC");
INSERT into Country values ("AND", "Andorra", "Andorra la Vella", "Developed", "Southern Europe", "EU");
INSERT into Country values ("ANG", "Angola", "Luanda", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("AIA", "Anguilla", "The Valley", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("ROS", "Antarctica", "nan", "nan", "nan", "AN");
INSERT into Country values ("ATG", "Antigua & Barbuda", "St. John's", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("ARG", "Argentina", "Buenos Aires", "Developing", "Latin America and the Caribbean", "SA");
INSERT into Country values ("ARM", "Armenia", "Yerevan", "Developing", "Western Asia", "AS");
INSERT into Country values ("ARU", "Aruba", "Oranjestad", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("AUS", "Australia", "Canberra", "Developed", "Australia and New Zealand", "OC");
INSERT into Country values ("AUT", "Austria", "Vienna", "Developed", "Western Europe", "EU");
INSERT into Country values ("AZE", "Azerbaijan", "Baku", "Developing", "Western Asia", "AS");
INSERT into Country values ("BAH", "Bahamas", "Nassau", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("BHR", "Bahrain", "Manama", "Developing", "Western Asia", "AS");
INSERT into Country values ("BAN", "Bangladesh", "Dhaka", "Developing", "Southern Asia", "AS");
INSERT into Country values ("BRB", "Barbados", "Bridgetown", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("BLR", "Belarus", "Minsk", "Developed", "Eastern Europe", "EU");
INSERT into Country values ("BEL", "Belgium", "Brussels", "Developed", "Western Europe", "EU");
INSERT into Country values ("BLZ", "Belize", "Belmopan", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("BEN", "Benin", "Porto-Novo", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("BER", "Bermuda", "Hamilton", "Developed", "Northern America", "nan");
INSERT into Country values ("BHU", "Bhutan", "Thimphu", "Developing", "Southern Asia", "AS");
INSERT into Country values ("BOL", "Bolivia", "Sucre", "Developing", "Latin America and the Caribbean", "SA");
INSERT into Country values ("ANT", "Bonaire, Sint Eustatius and Saba", "nan", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("BIH", "Bosnia Herzegovina", "Sarajevo", "Developed", "Southern Europe", "EU");
INSERT into Country values ("BOT", "Botswana", "Gaborone", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("nan", "Bouvet Island", "nan", "Developing", "Latin America and the Caribbean", "AN");
INSERT into Country values ("BRA", "Brazil", "Brasilia", "Developing", "Latin America and the Caribbean", "SA");
INSERT into Country values ("nan", "British Indian Ocean Territory", "Diego Garcia", "Developing", "Sub-Saharan Africa", "AS");
INSERT into Country values ("VGB", "British Virgin Islands", "Road Town", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("BRU", "Brunei Darussalam", "Bandar Seri Begawan", "Developing", "South-eastern Asia", "AS");
INSERT into Country values ("BUL", "Bulgaria", "Sofia", "Developed", "Eastern Europe", "EU");
INSERT into Country values ("BFA", "Burkina Faso", "Ouagadougou", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("BDI", "Burundi", "Bujumbura", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("CPV", "Cape Verde", "Praia", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("CAM", "Cambodia", "Phnom Penh", "Developing", "South-eastern Asia", "AS");
INSERT into Country values ("CMR", "Cameroon", "Yaounde", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("CAN", "Canada", "Ottawa", "Developed", "Northern America", "nan");
INSERT into Country values ("CAY", "Cayman Islands", "George Town", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("CTA", "Central African Rep.", "Bangui", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("CHA", "Chad", "N'Djamena", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("CHI", "Chile", "Santiago", "Developing", "Latin America and the Caribbean", "SA");
INSERT into Country values ("CHN", "China PR", "Beijing", "Developing", "Eastern Asia", "AS");
INSERT into Country values ("HKG", "Hong Kong", "Hong Kong", "Developing", "Eastern Asia", "AS");
INSERT into Country values ("MAC", "China, Macao Special Administrative Region", "Macao", "Developing", "Eastern Asia", "AS");
INSERT into Country values ("CXR", "Christmas Island", "Flying Fish Cove", "Developed", "Australia and New Zealand", "AS");
INSERT into Country values ("CCK", "Cocos (Keeling) Islands", "West Island", "Developed", "Australia and New Zealand", "AS");
INSERT into Country values ("COL", "Colombia", "Bogota", "Developing", "Latin America and the Caribbean", "SA");
INSERT into Country values ("COM", "Comoros", "Moroni", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("CGO", "Congo", "Brazzaville", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("COK", "Cook Islands", "Avarua", "Developing", "Polynesia", "OC");
INSERT into Country values ("CRC", "Costa Rica", "San Jose", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("CRO", "Croatia", "Zagreb", "Developed", "Southern Europe", "EU");
INSERT into Country values ("CUB", "Cuba", "Havana", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("nan", "Curacao", " Willemstad", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("CYP", "Cyprus", "Nicosia", "Developing", "Western Asia", "EU");
INSERT into Country values ("CZE", "Czech Republic", "Prague", "Developed", "Eastern Europe", "EU");
INSERT into Country values ("CIV", "Ivory Coast", "Yamoussoukro", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("PRK", "Korea DPR", "Pyongyang", "Developing", "Eastern Asia", "AS");
INSERT into Country values ("COD", "DR Congo", "Kinshasa", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("DEN", "Denmark", "Copenhagen", "Developed", "Northern Europe", "EU");
INSERT into Country values ("DJI", "Djibouti", "Djibouti", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("DMA", "Dominica", "Roseau", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("DOM", "Dominican Republic", "Santo Domingo", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("ECU", "Ecuador", "Quito", "Developing", "Latin America and the Caribbean", "SA");
INSERT into Country values ("EGY", "Egypt", "Cairo", "Developing", "Northern Africa", "AF");
INSERT into Country values ("SLV", "El Salvador", "San Salvador", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("EQG", "Equatorial Guinea", "Malabo", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("ERI", "Eritrea", "Asmara", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("EST", "Estonia", "Tallinn", "Developed", "Northern Europe", "EU");
INSERT into Country values ("ETH", "Ethiopia", "Addis Ababa", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("FLK", "Falkland Islands (Malvinas)", "Stanley", "Developing", "Latin America and the Caribbean", "SA");
INSERT into Country values ("FRO", "Faroe Islands", "Torshavn", "Developed", "Northern Europe", "EU");
INSERT into Country values ("FIJ", "Fiji", "Suva", "Developing", "Melanesia", "OC");
INSERT into Country values ("FIN", "Finland", "Helsinki", "Developed", "Northern Europe", "EU");
INSERT into Country values ("FRA", "France", "Paris", "Developed", "Western Europe", "EU");
INSERT into Country values ("GUF", "French Guiana", "Cayenne", "Developing", "Latin America and the Caribbean", "SA");
INSERT into Country values ("TAH", "French Polynesia", "Papeete", "Developing", "Polynesia", "OC");
INSERT into Country values ("nan", "French Southern Territories", "Port-aux-Francais", "Developing", "Sub-Saharan Africa", "AN");
INSERT into Country values ("GAB", "Gabon", "Libreville", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("GAM", "Gambia", "Banjul", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("GEO", "Georgia", "Tbilisi", "Developing", "Western Asia", "AS");
INSERT into Country values ("GER", "Germany", "Berlin", "Developed", "Western Europe", "EU");
INSERT into Country values ("GHA", "Ghana", "Accra", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("GBZ", "Gibraltar", "Gibraltar", "Developed", "Southern Europe", "EU");
INSERT into Country values ("GRE", "Greece", "Athens", "Developed", "Southern Europe", "EU");
INSERT into Country values ("GRL", "Greenland", "Nuuk", "Developed", "Northern America", "nan");
INSERT into Country values ("GRN", "Grenada", "St. George's", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("GLP", "Guadeloupe", "Basse-Terre", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("GUM", "Guam", "Hagatna", "Developing", "Micronesia", "OC");
INSERT into Country values ("GUA", "Guatemala", "Guatemala City", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("GBG", "Guernsey", "St Peter Port", "Developed", "Northern Europe", "EU");
INSERT into Country values ("GUI", "Guinea", "Conakry", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("GNB", "Guinea Bissau", "Bissau", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("GUY", "Guyana", "Georgetown", "Developing", "Latin America and the Caribbean", "SA");
INSERT into Country values ("HAI", "Haiti", "Port-au-Prince", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("nan", "Heard Island and McDonald Islands", "nan", "Developed", "Australia and New Zealand", "AN");
INSERT into Country values ("VAT", "Holy See", "Vatican City", "Developed", "Southern Europe", "EU");
INSERT into Country values ("HON", "Honduras", "Tegucigalpa", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("HUN", "Hungary", "Budapest", "Developed", "Eastern Europe", "EU");
INSERT into Country values ("ISL", "Iceland", "Reykjavik", "Developed", "Northern Europe", "EU");
INSERT into Country values ("IND", "India", "New Delhi", "Developing", "Southern Asia", "AS");
INSERT into Country values ("IDN", "Indonesia", "Jakarta", "Developing", "South-eastern Asia", "AS");
INSERT into Country values ("IRN", "Iran", "Tehran", "Developing", "Southern Asia", "AS");
INSERT into Country values ("IRQ", "Iraq", "Baghdad", "Developing", "Western Asia", "AS");
INSERT into Country values ("IRL", "Republic of Ireland", "Dublin", "Developed", "Northern Europe", "EU");
INSERT into Country values ("GBM", "Isle of Man", "Douglas", "Developed", "Northern Europe", "EU");
INSERT into Country values ("ISR", "Israel", "Jerusalem", "Developing", "Western Asia", "AS");
INSERT into Country values ("ITA", "Italy", "Rome", "Developed", "Southern Europe", "EU");
INSERT into Country values ("JAM", "Jamaica", "Kingston", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("JPN", "Japan", "Tokyo", "Developed", "Eastern Asia", "AS");
INSERT into Country values ("GBJ", "Jersey", "Saint Helier", "Developed", "Northern Europe", "EU");
INSERT into Country values ("JOR", "Jordan", "Amman", "Developing", "Western Asia", "AS");
INSERT into Country values ("KAZ", "Kazakhstan", "Astana", "Developing", "Central Asia", "AS");
INSERT into Country values ("KEN", "Kenya", "Nairobi", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("KIR", "Kiribati", "Tarawa", "Developing", "Micronesia", "OC");
INSERT into Country values ("KUW", "Kuwait", "Kuwait City", "Developing", "Western Asia", "AS");
INSERT into Country values ("KGZ", "Kyrgyzstan", "Bishkek", "Developing", "Central Asia", "AS");
INSERT into Country values ("LAO", "Lao People's Democratic Republic", "Vientiane", "Developing", "South-eastern Asia", "AS");
INSERT into Country values ("LVA", "Latvia", "Riga", "Developed", "Northern Europe", "EU");
INSERT into Country values ("LIB", "Lebanon", "Beirut", "Developing", "Western Asia", "AS");
INSERT into Country values ("LES", "Lesotho", "Maseru", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("LBR", "Liberia", "Monrovia", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("LBY", "Libya", "Tripoli", "Developing", "Northern Africa", "AF");
INSERT into Country values ("LIE", "Liechtenstein", "Vaduz", "Developed", "Western Europe", "EU");
INSERT into Country values ("LTU", "Lithuania", "Vilnius", "Developed", "Northern Europe", "EU");
INSERT into Country values ("LUX", "Luxembourg", "Luxembourg", "Developed", "Western Europe", "EU");
INSERT into Country values ("MAD", "Madagascar", "Antananarivo", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("MWI", "Malawi", "Lilongwe", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("MAS", "Malaysia", "Kuala Lumpur", "Developing", "South-eastern Asia", "AS");
INSERT into Country values ("MDV", "Maldives", "Male", "Developing", "Southern Asia", "AS");
INSERT into Country values ("MLI", "Mali", "Bamako", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("MLT", "Malta", "Valletta", "Developed", "Southern Europe", "EU");
INSERT into Country values ("MHL", "Marshall Islands", "Majuro", "Developing", "Micronesia", "OC");
INSERT into Country values ("MTQ", "Martinique", "Fort-de-France", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("MTN", "Mauritania", "Nouakchott", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("MRI", "Mauritius", "Port Louis", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("MYT", "Mayotte", "Mamoudzou", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("MEX", "Mexico", "Mexico City", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("FSM", "Micronesia (Federated States of)", "Palikir", "Developing", "Micronesia", "OC");
INSERT into Country values ("MON", "Monaco", "Monaco", "Developed", "Western Europe", "EU");
INSERT into Country values ("MNG", "Mongolia", "Ulan Bator", "Developing", "Eastern Asia", "AS");
INSERT into Country values ("MNE", "Montenegro", "Podgorica", "Developed", "Southern Europe", "EU");
INSERT into Country values ("MSR", "Montserrat", "Plymouth", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("MAR", "Morocco", "Rabat", "Developing", "Northern Africa", "AF");
INSERT into Country values ("MOZ", "Mozambique", "Maputo", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("MYA", "Myanmar", "Nay Pyi Taw", "Developing", "South-eastern Asia", "AS");
INSERT into Country values ("NAM", "Namibia", "Windhoek", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("NRU", "Nauru", "Yaren", "Developing", "Micronesia", "OC");
INSERT into Country values ("NEP", "Nepal", "Kathmandu", "Developing", "Southern Asia", "AS");
INSERT into Country values ("NED", "Netherlands", "Amsterdam", "Developed", "Western Europe", "EU");
INSERT into Country values ("NCL", "New Caledonia", "Noumea", "Developing", "Melanesia", "OC");
INSERT into Country values ("NZL", "New Zealand", "Wellington", "Developed", "Australia and New Zealand", "OC");
INSERT into Country values ("NCA", "Nicaragua", "Managua", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("NIG", "Niger", "Niamey", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("NGA", "Nigeria", "Abuja", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("NIU", "Niue", "Alofi", "Developing", "Polynesia", "OC");
INSERT into Country values ("NFK", "Norfolk Island", "Kingston", "Developed", "Australia and New Zealand", "OC");
INSERT into Country values ("NMI", "Northern Mariana Islands", "Saipan", "Developing", "Micronesia", "OC");
INSERT into Country values ("NOR", "Norway", "Oslo", "Developed", "Northern Europe", "EU");
INSERT into Country values ("OMA", "Oman", "Muscat", "Developing", "Western Asia", "AS");
INSERT into Country values ("PAK", "Pakistan", "Islamabad", "Developing", "Southern Asia", "AS");
INSERT into Country values ("PLW", "Palau", "Melekeok", "Developing", "Micronesia", "OC");
INSERT into Country values ("PAN", "Panama", "Panama City", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("PNG", "Papua New Guinea", "Port Moresby", "Developing", "Melanesia", "OC");
INSERT into Country values ("PAR", "Paraguay", "Asuncion", "Developing", "Latin America and the Caribbean", "SA");
INSERT into Country values ("PER", "Peru", "Lima", "Developing", "Latin America and the Caribbean", "SA");
INSERT into Country values ("PHI", "Philippines", "Manila", "Developing", "South-eastern Asia", "AS");
INSERT into Country values ("PCN", "Pitcairn", "Adamstown", "Developing", "Polynesia", "OC");
INSERT into Country values ("POL", "Poland", "Warsaw", "Developed", "Eastern Europe", "EU");
INSERT into Country values ("POR", "Portugal", "Lisbon", "Developed", "Southern Europe", "EU");
INSERT into Country values ("PUR", "Puerto Rico", "San Juan", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("QAT", "Qatar", "Doha", "Developing", "Western Asia", "AS");
INSERT into Country values ("KOR", "Korea Republic", "Seoul", "Developing", "Eastern Asia", "AS");
INSERT into Country values ("MDA", "Moldova", "Chisinau", "Developed", "Eastern Europe", "EU");
INSERT into Country values ("ROU", "Romania", "Bucharest", "Developed", "Eastern Europe", "EU");
INSERT into Country values ("RUS", "Russia", "Moscow", "Developed", "Eastern Europe", "EU");
INSERT into Country values ("RWA", "Rwanda", "Kigali", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("REU", "R©union", "Saint-Denis", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("Î¾", "Saint Barth©lemy", "Gustavia", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("SHN", "Saint Helena", "Jamestown", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("SKN", "St Kitts Nevis", "Basseterre", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("LCA", "St Lucia", "Castries", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("Î¾", "Saint Martin (French Part)", "Marigot", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("SPM", "Saint Pierre and Miquelon", "Saint-Pierre", "Developed", "Northern America", "nan");
INSERT into Country values ("VIN", "Saint Vincent and the Grenadines", "Kingstown", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("SAM", "Samoa", "Apia", "Developing", "Polynesia", "OC");
INSERT into Country values ("SMR", "San Marino", "San Marino", "Developed", "Southern Europe", "EU");
INSERT into Country values ("STP", "S£o Tom© & Pr_ncipe", "Sao Tome", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("nan", "Sark", "nan", "Developed", "Northern Europe", "nan");
INSERT into Country values ("KSA", "Saudi Arabia", "Riyadh", "Developing", "Western Asia", "AS");
INSERT into Country values ("SEN", "Senegal", "Dakar", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("SRB", "Serbia", "Belgrade", "Developed", "Southern Europe", "EU");
INSERT into Country values ("SEY", "Seychelles", "Victoria", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("SLE", "Sierra Leone", "Freetown", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("SIN", "Singapore", "Singapore", "Developing", "South-eastern Asia", "AS");
INSERT into Country values ("nan", "Sint Maarten (Dutch part)", "Philipsburg", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("SVK", "Slovakia", "Bratislava", "Developed", "Eastern Europe", "EU");
INSERT into Country values ("SVN", "Slovenia", "Ljubljana", "Developed", "Southern Europe", "EU");
INSERT into Country values ("SOL", "Solomon Islands", "Honiara", "Developing", "Melanesia", "OC");
INSERT into Country values ("SOM", "Somalia", "Mogadishu", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("RSA", "South Africa", "Pretoria", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("nan", "South Georgia and the South Sandwich Islands", "Grytviken", "Developing", "Latin America and the Caribbean", "AN");
INSERT into Country values ("nan", "South Sudan", "Juba", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("ESP", "Spain", "Madrid", "Developed", "Southern Europe", "EU");
INSERT into Country values ("SRI", "Sri Lanka", "Colombo", "Developing", "Southern Asia", "AS");
INSERT into Country values ("PLE", "Palestine", "East Jerusalem", "Developing", "Western Asia", "AS");
INSERT into Country values ("SUD", "Sudan", "Khartoum", "Developing", "Northern Africa", "AF");
INSERT into Country values ("SUR", "Suriname", "Paramaribo", "Developing", "Latin America and the Caribbean", "SA");
INSERT into Country values ("nan", "Svalbard and Jan Mayen Islands", "Longyearbyen", "Developed", "Northern Europe", "EU");
INSERT into Country values ("SWZ", "Swaziland", "Mbabane", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("SWE", "Sweden", "Stockholm", "Developed", "Northern Europe", "EU");
INSERT into Country values ("SUI", "Switzerland", "Bern", "Developed", "Western Europe", "EU");
INSERT into Country values ("SYR", "Syria", "Damascus", "Developing", "Western Asia", "AS");
INSERT into Country values ("TJK", "Tajikistan", "Dushanbe", "Developing", "Central Asia", "AS");
INSERT into Country values ("THA", "Thailand", "Bangkok", "Developing", "South-eastern Asia", "AS");
INSERT into Country values ("MKD", "FYR Macedonia", "Skopje", "Developed", "Southern Europe", "EU");
INSERT into Country values ("TLS", "Timor-Leste", "Dili", "Developing", "South-eastern Asia", "OC");
INSERT into Country values ("TOG", "Togo", "Lome", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("TKL", "Tokelau", "nan", "Developing", "Polynesia", "OC");
INSERT into Country values ("TGA", "Tonga", "Nuku'alofa", "Developing", "Polynesia", "OC");
INSERT into Country values ("TRI", "Trinidad & Tobago", "Port of Spain", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("TUN", "Tunisia", "Tunis", "Developing", "Northern Africa", "AF");
INSERT into Country values ("TUR", "Turkey", "Ankara", "Developing", "Western Asia", "AS");
INSERT into Country values ("TKM", "Turkmenistan", "Ashgabat", "Developing", "Central Asia", "AS");
INSERT into Country values ("TCA", "Turks and Caicos Islands", "Cockburn Town", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("TUV", "Tuvalu", "Funafuti", "Developing", "Polynesia", "OC");
INSERT into Country values ("UGA", "Uganda", "Kampala", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("UKR", "Ukraine", "Kiev", "Developed", "Eastern Europe", "EU");
INSERT into Country values ("UAE", "United Arab Emirates", "Abu Dhabi", "Developing", "Western Asia", "AS");
INSERT into Country values ("ENG", "England", "London", "Developed", "Northern Europe", "EU");
INSERT into Country values ("TAN", "Tanzania", "Dodoma", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("nan", "United States Minor Outlying Islands", "nan", "Developing", "Micronesia", "OC");
INSERT into Country values ("VIR", "United States Virgin Islands", "Charlotte Amalie", "Developing", "Latin America and the Caribbean", "nan");
INSERT into Country values ("USA", "United States", "Washington", "Developed", "Northern America", "nan");
INSERT into Country values ("URU", "Uruguay", "Montevideo", "Developing", "Latin America and the Caribbean", "SA");
INSERT into Country values ("UZB", "Uzbekistan", "Tashkent", "Developing", "Central Asia", "AS");
INSERT into Country values ("VAN", "Vanuatu", "Port Vila", "Developing", "Melanesia", "OC");
INSERT into Country values ("VEN", "Venezuela", "Caracas", "Developing", "Latin America and the Caribbean", "SA");
INSERT into Country values ("VIE", "Vietnam", "Hanoi", "Developing", "South-eastern Asia", "AS");
INSERT into Country values ("WLF", "Wallis and Futuna Islands", "Mata Utu", "Developing", "Polynesia", "OC");
INSERT into Country values ("SAH", "Western Sahara", "El-Aaiun", "Developing", "Northern Africa", "AF");
INSERT into Country values ("YEM", "Yemen", "Sanaa", "Developing", "Western Asia", "AS");
INSERT into Country values ("ZAM", "Zambia", "Lusaka", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("ZIM", "Zimbabwe", "Harare", "Developing", "Sub-Saharan Africa", "AF");
INSERT into Country values ("ALD", "Äland Islands", "Mariehamn", "Developed", "Northern Europe", "EU");
INSERT into Country values ("RKS", "Kosovo", "Pristina", "Developing", "Southern Europe", "EU");
INSERT into Country values ("NIR", "Northern Ireland", "Belfast", "Developed", "Northern Europe", "EU");
INSERT into Country values ("SCT", "Scotland", "Edinburgh", "Developed", "Northern Europe", "EU");
INSERT into Country values ("WAL", "Wales", "Cardiff", "Developed", "Northern Europe", "EU");
